package com.xtr.api.domain.app;

import java.io.Serializable;
import java.util.Date;

public class AppQuestionFeedbackBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_question_feedback.feedback_id
     *ID
     * @mbggenerated
     */
    private Long feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_question_feedback.feedback_user_id
     *用户ID
     * @mbggenerated
     */
    private Long feedbackUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_question_feedback.feedback_type
     *反馈类型 1工资反馈 2APP反馈
     * @mbggenerated
     */
    private Integer feedbackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_question_feedback.feedback_createTime
     *反馈创建时间
     * @mbggenerated
     */
    private Date feedbackCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_question_feedback.feedback_updateTime
     *反馈更新时间
     * @mbggenerated
     */
    private Date feedbackUpdatetime;

    //问题的内容
    private String feedbackContent;

    public String getFeedbackContent() {
        return feedbackContent;
    }

    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_question_feedback.feedback_id
     *
     * @return the value of app_question_feedback.feedback_id
     *
     * @mbggenerated
     */
    public Long getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_question_feedback.feedback_id
     *
     * @param feedbackId the value for app_question_feedback.feedback_id
     *
     * @mbggenerated
     */
    public void setFeedbackId(Long feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_question_feedback.feedback_user_id
     *
     * @return the value of app_question_feedback.feedback_user_id
     *
     * @mbggenerated
     */
    public Long getFeedbackUserId() {
        return feedbackUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_question_feedback.feedback_user_id
     *
     * @param feedbackUserId the value for app_question_feedback.feedback_user_id
     *
     * @mbggenerated
     */
    public void setFeedbackUserId(Long feedbackUserId) {
        this.feedbackUserId = feedbackUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_question_feedback.feedback_type
     *
     * @return the value of app_question_feedback.feedback_type
     *
     * @mbggenerated
     */
    public Integer getFeedbackType() {
        return feedbackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_question_feedback.feedback_type
     *
     * @param feedbackType the value for app_question_feedback.feedback_type
     *
     * @mbggenerated
     */
    public void setFeedbackType(Integer feedbackType) {
        this.feedbackType = feedbackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_question_feedback.feedback_createTime
     *
     * @return the value of app_question_feedback.feedback_createTime
     *
     * @mbggenerated
     */
    public Date getFeedbackCreatetime() {
        return feedbackCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_question_feedback.feedback_createTime
     *
     * @param feedbackCreatetime the value for app_question_feedback.feedback_createTime
     *
     * @mbggenerated
     */
    public void setFeedbackCreatetime(Date feedbackCreatetime) {
        this.feedbackCreatetime = feedbackCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_question_feedback.feedback_updateTime
     *
     * @return the value of app_question_feedback.feedback_updateTime
     *
     * @mbggenerated
     */
    public Date getFeedbackUpdatetime() {
        return feedbackUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_question_feedback.feedback_updateTime
     *
     * @param feedbackUpdatetime the value for app_question_feedback.feedback_updateTime
     *
     * @mbggenerated
     */
    public void setFeedbackUpdatetime(Date feedbackUpdatetime) {
        this.feedbackUpdatetime = feedbackUpdatetime;
    }
}