package com.xtr.api.domain.company;

import com.xtr.api.basic.BaseObject;

import java.io.Serializable;
import java.util.Date;

public class CompanyNotesBean extends BaseObject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.note_id
     *
     * @mbggenerated
     */
    private Long noteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.note_title
     *
     * @mbggenerated
     */
    private String noteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.note_content
     *
     * @mbggenerated
     */
    private String noteContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.sys_user_id
     *
     * @mbggenerated
     */
    private Long sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.sys_user_name
     *
     * @mbggenerated
     */
    private String sysUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.record_time
     *
     * @mbggenerated
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_notes.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.note_id
     *
     * @return the value of company_notes.note_id
     *
     * @mbggenerated
     */
    public Long getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.note_id
     *
     * @param noteId the value for company_notes.note_id
     *
     * @mbggenerated
     */
    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.note_title
     *
     * @return the value of company_notes.note_title
     *
     * @mbggenerated
     */
    public String getNoteTitle() {
        return noteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.note_title
     *
     * @param noteTitle the value for company_notes.note_title
     *
     * @mbggenerated
     */
    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle == null ? null : noteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.company_id
     *
     * @return the value of company_notes.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.company_id
     *
     * @param companyId the value for company_notes.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.note_content
     *
     * @return the value of company_notes.note_content
     *
     * @mbggenerated
     */
    public String getNoteContent() {
        return noteContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.note_content
     *
     * @param noteContent the value for company_notes.note_content
     *
     * @mbggenerated
     */
    public void setNoteContent(String noteContent) {
        this.noteContent = noteContent == null ? null : noteContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.sys_user_id
     *
     * @return the value of company_notes.sys_user_id
     *
     * @mbggenerated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.sys_user_id
     *
     * @param sysUserId the value for company_notes.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.sys_user_name
     *
     * @return the value of company_notes.sys_user_name
     *
     * @mbggenerated
     */
    public String getSysUserName() {
        return sysUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.sys_user_name
     *
     * @param sysUserName the value for company_notes.sys_user_name
     *
     * @mbggenerated
     */
    public void setSysUserName(String sysUserName) {
        this.sysUserName = sysUserName == null ? null : sysUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.record_time
     *
     * @return the value of company_notes.record_time
     *
     * @mbggenerated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.record_time
     *
     * @param recordTime the value for company_notes.record_time
     *
     * @mbggenerated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_notes.del_flag
     *
     * @return the value of company_notes.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_notes.del_flag
     *
     * @param delFlag the value for company_notes.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}