package com.xtr.api.domain.company;

import java.io.Serializable;
import java.util.Date;

public class CompanyMsgsBean implements Serializable {

    private  String addTimeStr;

    public String getAddTimeStr() {
        return addTimeStr;
    }

    public void setAddTimeStr(String addTimeStr) {
        this.addTimeStr = addTimeStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_id
     *
     * @mbggenerated
     */
    private Long msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_title
     *
     * @mbggenerated
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_cont
     *
     * @mbggenerated
     */
    private String msgCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_type
     *
     * @mbggenerated
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_addtime
     *
     * @mbggenerated
     */
    private Date msgAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_company_id
     *
     * @mbggenerated
     */
    private Long msgCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_company_name
     *
     * @mbggenerated
     */
    private String msgCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_dep_id
     *
     * @mbggenerated
     */
    private Long msgDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_from_company_id
     *
     * @mbggenerated
     */
    private Long msgFromCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_from_company_name
     *
     * @mbggenerated
     */
    private String msgFromCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_sign
     *
     * @mbggenerated
     */
    private Integer msgSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_msgs.msg_class
     *
     * @mbggenerated
     */
    private Integer msgClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_id
     *
     * @return the value of company_msgs.msg_id
     *
     * @mbggenerated
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_id
     *
     * @param msgId the value for company_msgs.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_title
     *
     * @return the value of company_msgs.msg_title
     *
     * @mbggenerated
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_title
     *
     * @param msgTitle the value for company_msgs.msg_title
     *
     * @mbggenerated
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_cont
     *
     * @return the value of company_msgs.msg_cont
     *
     * @mbggenerated
     */
    public String getMsgCont() {
        return msgCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_cont
     *
     * @param msgCont the value for company_msgs.msg_cont
     *
     * @mbggenerated
     */
    public void setMsgCont(String msgCont) {
        this.msgCont = msgCont == null ? null : msgCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_type
     *
     * @return the value of company_msgs.msg_type
     *
     * @mbggenerated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_type
     *
     * @param msgType the value for company_msgs.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_addtime
     *
     * @return the value of company_msgs.msg_addtime
     *
     * @mbggenerated
     */
    public Date getMsgAddtime() {
        return msgAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_addtime
     *
     * @param msgAddtime the value for company_msgs.msg_addtime
     *
     * @mbggenerated
     */
    public void setMsgAddtime(Date msgAddtime) {
        this.msgAddtime = msgAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_company_id
     *
     * @return the value of company_msgs.msg_company_id
     *
     * @mbggenerated
     */
    public Long getMsgCompanyId() {
        return msgCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_company_id
     *
     * @param msgCompanyId the value for company_msgs.msg_company_id
     *
     * @mbggenerated
     */
    public void setMsgCompanyId(Long msgCompanyId) {
        this.msgCompanyId = msgCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_company_name
     *
     * @return the value of company_msgs.msg_company_name
     *
     * @mbggenerated
     */
    public String getMsgCompanyName() {
        return msgCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_company_name
     *
     * @param msgCompanyName the value for company_msgs.msg_company_name
     *
     * @mbggenerated
     */
    public void setMsgCompanyName(String msgCompanyName) {
        this.msgCompanyName = msgCompanyName == null ? null : msgCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_dep_id
     *
     * @return the value of company_msgs.msg_dep_id
     *
     * @mbggenerated
     */
    public Long getMsgDepId() {
        return msgDepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_dep_id
     *
     * @param msgDepId the value for company_msgs.msg_dep_id
     *
     * @mbggenerated
     */
    public void setMsgDepId(Long msgDepId) {
        this.msgDepId = msgDepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_from_company_id
     *
     * @return the value of company_msgs.msg_from_company_id
     *
     * @mbggenerated
     */
    public Long getMsgFromCompanyId() {
        return msgFromCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_from_company_id
     *
     * @param msgFromCompanyId the value for company_msgs.msg_from_company_id
     *
     * @mbggenerated
     */
    public void setMsgFromCompanyId(Long msgFromCompanyId) {
        this.msgFromCompanyId = msgFromCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_from_company_name
     *
     * @return the value of company_msgs.msg_from_company_name
     *
     * @mbggenerated
     */
    public String getMsgFromCompanyName() {
        return msgFromCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_from_company_name
     *
     * @param msgFromCompanyName the value for company_msgs.msg_from_company_name
     *
     * @mbggenerated
     */
    public void setMsgFromCompanyName(String msgFromCompanyName) {
        this.msgFromCompanyName = msgFromCompanyName == null ? null : msgFromCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_sign
     *
     * @return the value of company_msgs.msg_sign
     *
     * @mbggenerated
     */
    public Integer getMsgSign() {
        return msgSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_sign
     *
     * @param msgSign the value for company_msgs.msg_sign
     *
     * @mbggenerated
     */
    public void setMsgSign(Integer msgSign) {
        this.msgSign = msgSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_msgs.msg_class
     *
     * @return the value of company_msgs.msg_class
     *
     * @mbggenerated
     */
    public Integer getMsgClass() {
        return msgClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_msgs.msg_class
     *
     * @param msgClass the value for company_msgs.msg_class
     *
     * @mbggenerated
     */
    public void setMsgClass(Integer msgClass) {
        this.msgClass = msgClass;
    }
}