package com.xtr.api.domain.customer;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CustomersRecordBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_id
     *
     * @mbggenerated
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_customer_id
     *
     * @mbggenerated
     */
    private Long recordCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_operation_type
     *
     * @mbggenerated
     */
    private Integer recordOperationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_operation_time
     *
     * @mbggenerated
     */
    private Date recordOperationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dept_id
     *
     * @mbggenerated
     */
    private Long recordDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dept_name
     *
     * @mbggenerated
     */
    private String recordDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_arrive_time
     *
     * @mbggenerated
     */
    private Date recordArriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_station_reason
     *
     * @mbggenerated
     */
    private String recordStationReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dimissing_type
     *
     * @mbggenerated
     */
    private Integer recordDimissingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dimissing_time
     *
     * @mbggenerated
     */
    private Date recordDimissingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_compensation
     *
     * @mbggenerated
     */
    private BigDecimal recordCompensation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dimissing_reason
     *
     * @mbggenerated
     */
    private String recordDimissingReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_create_time
     *
     * @mbggenerated
     */
    private Date recordCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_update_time
     *
     * @mbggenerated
     */
    private Date recordUpdateTime;

    //调岗前部门ID
    private Long recordDeptIdBefore;
    //调岗前岗位
    private String recordStationNameBefore;
    //调岗后岗位
    private String recordStationNameAfter;
    //调薪前工资
    private BigDecimal recordSalaryBefore;
    //调薪后工资
    private BigDecimal recordSalaryAfter;

    public Long getRecordDeptIdBefore() {
        return recordDeptIdBefore;
    }

    public void setRecordDeptIdBefore(Long recordDeptIdBefore) {
        this.recordDeptIdBefore = recordDeptIdBefore;
    }

    public String getRecordStationNameBefore() {
        return recordStationNameBefore;
    }

    public void setRecordStationNameBefore(String recordStationNameBefore) {
        this.recordStationNameBefore = recordStationNameBefore;
    }

    public String getRecordStationNameAfter() {
        return recordStationNameAfter;
    }

    public void setRecordStationNameAfter(String recordStationNameAfter) {
        this.recordStationNameAfter = recordStationNameAfter;
    }

    public BigDecimal getRecordSalaryBefore() {
        return recordSalaryBefore;
    }

    public void setRecordSalaryBefore(BigDecimal recordSalaryBefore) {
        this.recordSalaryBefore = recordSalaryBefore;
    }

    public BigDecimal getRecordSalaryAfter() {
        return recordSalaryAfter;
    }

    public void setRecordSalaryAfter(BigDecimal recordSalaryAfter) {
        this.recordSalaryAfter = recordSalaryAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_id
     *
     * @return the value of customers_record.record_id
     *
     * @mbggenerated
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_id
     *
     * @param recordId the value for customers_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_customer_id
     *
     * @return the value of customers_record.record_customer_id
     *
     * @mbggenerated
     */
    public Long getRecordCustomerId() {
        return recordCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_customer_id
     *
     * @param recordCustomerId the value for customers_record.record_customer_id
     *
     * @mbggenerated
     */
    public void setRecordCustomerId(Long recordCustomerId) {
        this.recordCustomerId = recordCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_operation_type
     *
     * @return the value of customers_record.record_operation_type
     *
     * @mbggenerated
     */
    public Integer getRecordOperationType() {
        return recordOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_operation_type
     *
     * @param recordOperationType the value for customers_record.record_operation_type
     *
     * @mbggenerated
     */
    public void setRecordOperationType(Integer recordOperationType) {
        this.recordOperationType = recordOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_operation_time
     *
     * @return the value of customers_record.record_operation_time
     *
     * @mbggenerated
     */
    public Date getRecordOperationTime() {
        return recordOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_operation_time
     *
     * @param recordOperationTime the value for customers_record.record_operation_time
     *
     * @mbggenerated
     */
    public void setRecordOperationTime(Date recordOperationTime) {
        this.recordOperationTime = recordOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_dept_id
     *
     * @return the value of customers_record.record_dept_id
     *
     * @mbggenerated
     */
    public Long getRecordDeptId() {
        return recordDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_dept_id
     *
     * @param recordDeptId the value for customers_record.record_dept_id
     *
     * @mbggenerated
     */
    public void setRecordDeptId(Long recordDeptId) {
        this.recordDeptId = recordDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_dept_name
     *
     * @return the value of customers_record.record_dept_name
     *
     * @mbggenerated
     */
    public String getRecordDeptName() {
        return recordDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_dept_name
     *
     * @param recordDeptName the value for customers_record.record_dept_name
     *
     * @mbggenerated
     */
    public void setRecordDeptName(String recordDeptName) {
        this.recordDeptName = recordDeptName == null ? null : recordDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_arrive_time
     *
     * @return the value of customers_record.record_arrive_time
     *
     * @mbggenerated
     */
    public Date getRecordArriveTime() {
        return recordArriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_arrive_time
     *
     * @param recordArriveTime the value for customers_record.record_arrive_time
     *
     * @mbggenerated
     */
    public void setRecordArriveTime(Date recordArriveTime) {
        this.recordArriveTime = recordArriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_station_reason
     *
     * @return the value of customers_record.record_station_reason
     *
     * @mbggenerated
     */
    public String getRecordStationReason() {
        return recordStationReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_station_reason
     *
     * @param recordStationReason the value for customers_record.record_station_reason
     *
     * @mbggenerated
     */
    public void setRecordStationReason(String recordStationReason) {
        this.recordStationReason = recordStationReason == null ? null : recordStationReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_dimissing_type
     *
     * @return the value of customers_record.record_dimissing_type
     *
     * @mbggenerated
     */
    public Integer getRecordDimissingType() {
        return recordDimissingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_dimissing_type
     *
     * @param recordDimissingType the value for customers_record.record_dimissing_type
     *
     * @mbggenerated
     */
    public void setRecordDimissingType(Integer recordDimissingType) {
        this.recordDimissingType = recordDimissingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_dimissing_time
     *
     * @return the value of customers_record.record_dimissing_time
     *
     * @mbggenerated
     */
    public Date getRecordDimissingTime() {
        return recordDimissingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_dimissing_time
     *
     * @param recordDimissingTime the value for customers_record.record_dimissing_time
     *
     * @mbggenerated
     */
    public void setRecordDimissingTime(Date recordDimissingTime) {
        this.recordDimissingTime = recordDimissingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_compensation
     *
     * @return the value of customers_record.record_compensation
     *
     * @mbggenerated
     */
    public BigDecimal getRecordCompensation() {
        return recordCompensation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_compensation
     *
     * @param recordCompensation the value for customers_record.record_compensation
     *
     * @mbggenerated
     */
    public void setRecordCompensation(BigDecimal recordCompensation) {
        this.recordCompensation = recordCompensation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_dimissing_reason
     *
     * @return the value of customers_record.record_dimissing_reason
     *
     * @mbggenerated
     */
    public String getRecordDimissingReason() {
        return recordDimissingReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_dimissing_reason
     *
     * @param recordDimissingReason the value for customers_record.record_dimissing_reason
     *
     * @mbggenerated
     */
    public void setRecordDimissingReason(String recordDimissingReason) {
        this.recordDimissingReason = recordDimissingReason == null ? null : recordDimissingReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_create_time
     *
     * @return the value of customers_record.record_create_time
     *
     * @mbggenerated
     */
    public Date getRecordCreateTime() {
        return recordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_create_time
     *
     * @param recordCreateTime the value for customers_record.record_create_time
     *
     * @mbggenerated
     */
    public void setRecordCreateTime(Date recordCreateTime) {
        this.recordCreateTime = recordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_record.record_update_time
     *
     * @return the value of customers_record.record_update_time
     *
     * @mbggenerated
     */
    public Date getRecordUpdateTime() {
        return recordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_record.record_update_time
     *
     * @param recordUpdateTime the value for customers_record.record_update_time
     *
     * @mbggenerated
     */
    public void setRecordUpdateTime(Date recordUpdateTime) {
        this.recordUpdateTime = recordUpdateTime;
    }
}