package com.xtr.api.domain.customer;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CustomerExpenseDetailBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.cycle_id
     *
     * @mbggenerated
     */
    private Long cycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.expense_type
     *
     * @mbggenerated
     */
    private String expenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.expense_date
     *
     * @mbggenerated
     */
    private Date expenseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.expense_amount
     *
     * @mbggenerated
     */
    private BigDecimal expenseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_expense_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.id
     *
     * @return the value of customer_expense_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.id
     *
     * @param id the value for customer_expense_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.cycle_id
     *
     * @return the value of customer_expense_detail.cycle_id
     *
     * @mbggenerated
     */
    public Long getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.cycle_id
     *
     * @param cycleId the value for customer_expense_detail.cycle_id
     *
     * @mbggenerated
     */
    public void setCycleId(Long cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.company_id
     *
     * @return the value of customer_expense_detail.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.company_id
     *
     * @param companyId the value for customer_expense_detail.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.customer_id
     *
     * @return the value of customer_expense_detail.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.customer_id
     *
     * @param customerId the value for customer_expense_detail.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.expense_type
     *
     * @return the value of customer_expense_detail.expense_type
     *
     * @mbggenerated
     */
    public String getExpenseType() {
        return expenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.expense_type
     *
     * @param expenseType the value for customer_expense_detail.expense_type
     *
     * @mbggenerated
     */
    public void setExpenseType(String expenseType) {
        this.expenseType = expenseType == null ? null : expenseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.expense_date
     *
     * @return the value of customer_expense_detail.expense_date
     *
     * @mbggenerated
     */
    public Date getExpenseDate() {
        return expenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.expense_date
     *
     * @param expenseDate the value for customer_expense_detail.expense_date
     *
     * @mbggenerated
     */
    public void setExpenseDate(Date expenseDate) {
        this.expenseDate = expenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.expense_amount
     *
     * @return the value of customer_expense_detail.expense_amount
     *
     * @mbggenerated
     */
    public BigDecimal getExpenseAmount() {
        return expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.expense_amount
     *
     * @param expenseAmount the value for customer_expense_detail.expense_amount
     *
     * @mbggenerated
     */
    public void setExpenseAmount(BigDecimal expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.create_time
     *
     * @return the value of customer_expense_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.create_time
     *
     * @param createTime the value for customer_expense_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_expense_detail.update_time
     *
     * @return the value of customer_expense_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_expense_detail.update_time
     *
     * @param updateTime the value for customer_expense_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}