package com.xtr.api.domain.customer;

import com.xtr.api.basic.BaseObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CustomerShebaoOrderBean extends BaseObject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.company_shebao_order_id
     *
     * @mbggenerated
     */
    private Long companyShebaoOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.shebao_type
     *
     * @mbggenerated
     */
    private String shebaoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.require_type
     *
     * @mbggenerated
     */
    private Integer requireType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.order_base
     *
     * @mbggenerated
     */
    private BigDecimal orderBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.overdue_month
     *
     * @mbggenerated
     */
    private Date overdueMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.order_detail
     *
     * @mbggenerated
     */
    private String orderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.response_msg
     *
     * @mbggenerated
     */
    private String responseMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.payroll_status
     *
     * @mbggenerated
     */
    private Integer payrollStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.cycle_id
     *
     * @mbggenerated
     */
    private Long cycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.org_sum
     *
     * @mbggenerated
     */
    private BigDecimal orgSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.emp_sum
     *
     * @mbggenerated
     */
    private BigDecimal empSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.sbt_status
     *
     * @mbggenerated
     */
    private Integer sbtStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    //滞纳费
    private BigDecimal shebaoOrderOverdue;
    //社保通企业支付部份
    private BigDecimal shebaotongOrgPay;
    //社保通员工部份
    private BigDecimal shebaotongEmpPay;

    public BigDecimal getShebaotongOrgPay() {
        return shebaotongOrgPay;
    }

    public void setShebaotongOrgPay(BigDecimal shebaotongOrgPay) {
        this.shebaotongOrgPay = shebaotongOrgPay;
    }

    public BigDecimal getShebaotongEmpPay() {
        return shebaotongEmpPay;
    }

    public void setShebaotongEmpPay(BigDecimal shebaotongEmpPay) {
        this.shebaotongEmpPay = shebaotongEmpPay;
    }

    public BigDecimal getShebaoOrderOverdue() {
        return shebaoOrderOverdue;
    }

    public void setShebaoOrderOverdue(BigDecimal shebaoOrderOverdue) {
        this.shebaoOrderOverdue = shebaoOrderOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.id
     *
     * @return the value of customer_shebao_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.id
     *
     * @param id the value for customer_shebao_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.customer_id
     *
     * @return the value of customer_shebao_order.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.customer_id
     *
     * @param customerId the value for customer_shebao_order.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.company_shebao_order_id
     *
     * @return the value of customer_shebao_order.company_shebao_order_id
     *
     * @mbggenerated
     */
    public Long getCompanyShebaoOrderId() {
        return companyShebaoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.company_shebao_order_id
     *
     * @param companyShebaoOrderId the value for customer_shebao_order.company_shebao_order_id
     *
     * @mbggenerated
     */
    public void setCompanyShebaoOrderId(Long companyShebaoOrderId) {
        this.companyShebaoOrderId = companyShebaoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.shebao_type
     *
     * @return the value of customer_shebao_order.shebao_type
     *
     * @mbggenerated
     */
    public String getShebaoType() {
        return shebaoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.shebao_type
     *
     * @param shebaoType the value for customer_shebao_order.shebao_type
     *
     * @mbggenerated
     */
    public void setShebaoType(String shebaoType) {
        this.shebaoType = shebaoType == null ? null : shebaoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.require_type
     *
     * @return the value of customer_shebao_order.require_type
     *
     * @mbggenerated
     */
    public Integer getRequireType() {
        return requireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.require_type
     *
     * @param requireType the value for customer_shebao_order.require_type
     *
     * @mbggenerated
     */
    public void setRequireType(Integer requireType) {
        this.requireType = requireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.order_type
     *
     * @return the value of customer_shebao_order.order_type
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.order_type
     *
     * @param orderType the value for customer_shebao_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.order_base
     *
     * @return the value of customer_shebao_order.order_base
     *
     * @mbggenerated
     */
    public BigDecimal getOrderBase() {
        return orderBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.order_base
     *
     * @param orderBase the value for customer_shebao_order.order_base
     *
     * @mbggenerated
     */
    public void setOrderBase(BigDecimal orderBase) {
        this.orderBase = orderBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.overdue_month
     *
     * @return the value of customer_shebao_order.overdue_month
     *
     * @mbggenerated
     */
    public Date getOverdueMonth() {
        return overdueMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.overdue_month
     *
     * @param overdueMonth the value for customer_shebao_order.overdue_month
     *
     * @mbggenerated
     */
    public void setOverdueMonth(Date overdueMonth) {
        this.overdueMonth = overdueMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.order_detail
     *
     * @return the value of customer_shebao_order.order_detail
     *
     * @mbggenerated
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.order_detail
     *
     * @param orderDetail the value for customer_shebao_order.order_detail
     *
     * @mbggenerated
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail == null ? null : orderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.response_msg
     *
     * @return the value of customer_shebao_order.response_msg
     *
     * @mbggenerated
     */
    public String getResponseMsg() {
        return responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.response_msg
     *
     * @param responseMsg the value for customer_shebao_order.response_msg
     *
     * @mbggenerated
     */
    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg == null ? null : responseMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.status
     *
     * @return the value of customer_shebao_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.status
     *
     * @param status the value for customer_shebao_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.payroll_status
     *
     * @return the value of customer_shebao_order.payroll_status
     *
     * @mbggenerated
     */
    public Integer getPayrollStatus() {
        return payrollStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.payroll_status
     *
     * @param payrollStatus the value for customer_shebao_order.payroll_status
     *
     * @mbggenerated
     */
    public void setPayrollStatus(Integer payrollStatus) {
        this.payrollStatus = payrollStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.cycle_id
     *
     * @return the value of customer_shebao_order.cycle_id
     *
     * @mbggenerated
     */
    public Long getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.cycle_id
     *
     * @param cycleId the value for customer_shebao_order.cycle_id
     *
     * @mbggenerated
     */
    public void setCycleId(Long cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.org_sum
     *
     * @return the value of customer_shebao_order.org_sum
     *
     * @mbggenerated
     */
    public BigDecimal getOrgSum() {
        return orgSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.org_sum
     *
     * @param orgSum the value for customer_shebao_order.org_sum
     *
     * @mbggenerated
     */
    public void setOrgSum(BigDecimal orgSum) {
        this.orgSum = orgSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.emp_sum
     *
     * @return the value of customer_shebao_order.emp_sum
     *
     * @mbggenerated
     */
    public BigDecimal getEmpSum() {
        return empSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.emp_sum
     *
     * @param empSum the value for customer_shebao_order.emp_sum
     *
     * @mbggenerated
     */
    public void setEmpSum(BigDecimal empSum) {
        this.empSum = empSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.sbt_status
     *
     * @return the value of customer_shebao_order.sbt_status
     *
     * @mbggenerated
     */
    public Integer getSbtStatus() {
        return sbtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.sbt_status
     *
     * @param sbtStatus the value for customer_shebao_order.sbt_status
     *
     * @mbggenerated
     */
    public void setSbtStatus(Integer sbtStatus) {
        this.sbtStatus = sbtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order.create_time
     *
     * @return the value of customer_shebao_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order.create_time
     *
     * @param createTime the value for customer_shebao_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}