package com.xtr.api.domain.customer;

import java.io.Serializable;
import java.util.Date;

public class CustomersStationBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_customer_id
     *
     * @mbggenerated
     */
    private Long stationCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_enter_time
     *
     * @mbggenerated
     */
    private Date stationEnterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_employ_method
     *
     * @mbggenerated
     */
    private Integer stationEmployMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_regular_time
     *
     * @mbggenerated
     */
    private Date stationRegularTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_customer_number
     *
     * @mbggenerated
     */
    private String stationCustomerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_customer_state
     *
     * @mbggenerated
     */
    private Integer stationCustomerState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_dept_id
     *
     * @mbggenerated
     */
    private Long stationDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_station_name
     *
     * @mbggenerated
     */
    private String stationStationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_contract_file
     *
     * @mbggenerated
     */
    private String stationContractFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_regular_evaluate
     *
     * @mbggenerated
     */
    private String stationRegularEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_create_time
     *
     * @mbggenerated
     */
    private Date stationCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_update_time
     *
     * @mbggenerated
     */
    private Date stationUpdateTime;
    //离职日期
    private Date stationDimissingTime;
    //更新转正日期,更新为空
    private Integer checkRegularTime;

    public Integer getCheckRegularTime() {
        return checkRegularTime;
    }

    public void setCheckRegularTime(Integer checkRegularTime) {
        this.checkRegularTime = checkRegularTime;
    }

    public Date getStationDimissingTime() {
        return stationDimissingTime;
    }

    public void setStationDimissingTime(Date stationDimissingTime) {
        this.stationDimissingTime = stationDimissingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_id
     *
     * @return the value of customers_station.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_id
     *
     * @param stationId the value for customers_station.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_customer_id
     *
     * @return the value of customers_station.station_customer_id
     *
     * @mbggenerated
     */
    public Long getStationCustomerId() {
        return stationCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_customer_id
     *
     * @param stationCustomerId the value for customers_station.station_customer_id
     *
     * @mbggenerated
     */
    public void setStationCustomerId(Long stationCustomerId) {
        this.stationCustomerId = stationCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_enter_time
     *
     * @return the value of customers_station.station_enter_time
     *
     * @mbggenerated
     */
    public Date getStationEnterTime() {
        return stationEnterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_enter_time
     *
     * @param stationEnterTime the value for customers_station.station_enter_time
     *
     * @mbggenerated
     */
    public void setStationEnterTime(Date stationEnterTime) {
        this.stationEnterTime = stationEnterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_employ_method
     *
     * @return the value of customers_station.station_employ_method
     *
     * @mbggenerated
     */
    public Integer getStationEmployMethod() {
        return stationEmployMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_employ_method
     *
     * @param stationEmployMethod the value for customers_station.station_employ_method
     *
     * @mbggenerated
     */
    public void setStationEmployMethod(Integer stationEmployMethod) {
        this.stationEmployMethod = stationEmployMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_regular_time
     *
     * @return the value of customers_station.station_regular_time
     *
     * @mbggenerated
     */
    public Date getStationRegularTime() {
        return stationRegularTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_regular_time
     *
     * @param stationRegularTime the value for customers_station.station_regular_time
     *
     * @mbggenerated
     */
    public void setStationRegularTime(Date stationRegularTime) {
        this.stationRegularTime = stationRegularTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_customer_number
     *
     * @return the value of customers_station.station_customer_number
     *
     * @mbggenerated
     */
    public String getStationCustomerNumber() {
        return stationCustomerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_customer_number
     *
     * @param stationCustomerNumber the value for customers_station.station_customer_number
     *
     * @mbggenerated
     */
    public void setStationCustomerNumber(String stationCustomerNumber) {
        this.stationCustomerNumber = stationCustomerNumber == null ? null : stationCustomerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_customer_state
     *
     * @return the value of customers_station.station_customer_state
     *
     * @mbggenerated
     */
    public Integer getStationCustomerState() {
        return stationCustomerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_customer_state
     *
     * @param stationCustomerState the value for customers_station.station_customer_state
     *
     * @mbggenerated
     */
    public void setStationCustomerState(Integer stationCustomerState) {
        this.stationCustomerState = stationCustomerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_dept_id
     *
     * @return the value of customers_station.station_dept_id
     *
     * @mbggenerated
     */
    public Long getStationDeptId() {
        return stationDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_dept_id
     *
     * @param stationDeptId the value for customers_station.station_dept_id
     *
     * @mbggenerated
     */
    public void setStationDeptId(Long stationDeptId) {
        this.stationDeptId = stationDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_station_name
     *
     * @return the value of customers_station.station_station_name
     *
     * @mbggenerated
     */
    public String getStationStationName() {
        return stationStationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_station_name
     *
     * @param stationStationName the value for customers_station.station_station_name
     *
     * @mbggenerated
     */
    public void setStationStationName(String stationStationName) {
        this.stationStationName = stationStationName == null ? null : stationStationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_contract_file
     *
     * @return the value of customers_station.station_contract_file
     *
     * @mbggenerated
     */
    public String getStationContractFile() {
        return stationContractFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_contract_file
     *
     * @param stationContractFile the value for customers_station.station_contract_file
     *
     * @mbggenerated
     */
    public void setStationContractFile(String stationContractFile) {
        this.stationContractFile = stationContractFile == null ? null : stationContractFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_regular_evaluate
     *
     * @return the value of customers_station.station_regular_evaluate
     *
     * @mbggenerated
     */
    public String getStationRegularEvaluate() {
        return stationRegularEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_regular_evaluate
     *
     * @param stationRegularEvaluate the value for customers_station.station_regular_evaluate
     *
     * @mbggenerated
     */
    public void setStationRegularEvaluate(String stationRegularEvaluate) {
        this.stationRegularEvaluate = stationRegularEvaluate == null ? null : stationRegularEvaluate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_create_time
     *
     * @return the value of customers_station.station_create_time
     *
     * @mbggenerated
     */
    public Date getStationCreateTime() {
        return stationCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_create_time
     *
     * @param stationCreateTime the value for customers_station.station_create_time
     *
     * @mbggenerated
     */
    public void setStationCreateTime(Date stationCreateTime) {
        this.stationCreateTime = stationCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_station.station_update_time
     *
     * @return the value of customers_station.station_update_time
     *
     * @mbggenerated
     */
    public Date getStationUpdateTime() {
        return stationUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_station.station_update_time
     *
     * @param stationUpdateTime the value for customers_station.station_update_time
     *
     * @mbggenerated
     */
    public void setStationUpdateTime(Date stationUpdateTime) {
        this.stationUpdateTime = stationUpdateTime;
    }
}