package com.xtr.api.domain.customer;

import java.io.Serializable;
import java.util.Date;

public class CustomersPersonalBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_id
     *
     * @mbggenerated
     */
    private Long personalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_customer_id
     *
     * @mbggenerated
     */
    private Long personalCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_relationer_name
     *
     * @mbggenerated
     */
    private String personalRelationerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_relationer_phone
     *
     * @mbggenerated
     */
    private String personalRelationerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_domicile_place
     *
     * @mbggenerated
     */
    private String personalDomicilePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_nation
     *
     * @mbggenerated
     */
    private String personalNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_politics_status
     *
     * @mbggenerated
     */
    private String personalPoliticsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_current_place
     *
     * @mbggenerated
     */
    private String personalCurrentPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_education_high
     *
     * @mbggenerated
     */
    private Integer personalEducationHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_graduate_school
     *
     * @mbggenerated
     */
    private String personalGraduateSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_major
     *
     * @mbggenerated
     */
    private String personalMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_resume
     *
     * @mbggenerated
     */
    private String personalResume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_create_time
     *
     * @mbggenerated
     */
    private Date personalCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_update_time
     *
     * @mbggenerated
     */
    private Date personalUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_id
     *
     * @return the value of customers_personal.personal_id
     *
     * @mbggenerated
     */
    public Long getPersonalId() {
        return personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_id
     *
     * @param personalId the value for customers_personal.personal_id
     *
     * @mbggenerated
     */
    public void setPersonalId(Long personalId) {
        this.personalId = personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_customer_id
     *
     * @return the value of customers_personal.personal_customer_id
     *
     * @mbggenerated
     */
    public Long getPersonalCustomerId() {
        return personalCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_customer_id
     *
     * @param personalCustomerId the value for customers_personal.personal_customer_id
     *
     * @mbggenerated
     */
    public void setPersonalCustomerId(Long personalCustomerId) {
        this.personalCustomerId = personalCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_relationer_name
     *
     * @return the value of customers_personal.personal_relationer_name
     *
     * @mbggenerated
     */
    public String getPersonalRelationerName() {
        return personalRelationerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_relationer_name
     *
     * @param personalRelationerName the value for customers_personal.personal_relationer_name
     *
     * @mbggenerated
     */
    public void setPersonalRelationerName(String personalRelationerName) {
        this.personalRelationerName = personalRelationerName == null ? null : personalRelationerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_relationer_phone
     *
     * @return the value of customers_personal.personal_relationer_phone
     *
     * @mbggenerated
     */
    public String getPersonalRelationerPhone() {
        return personalRelationerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_relationer_phone
     *
     * @param personalRelationerPhone the value for customers_personal.personal_relationer_phone
     *
     * @mbggenerated
     */
    public void setPersonalRelationerPhone(String personalRelationerPhone) {
        this.personalRelationerPhone = personalRelationerPhone == null ? null : personalRelationerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_domicile_place
     *
     * @return the value of customers_personal.personal_domicile_place
     *
     * @mbggenerated
     */
    public String getPersonalDomicilePlace() {
        return personalDomicilePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_domicile_place
     *
     * @param personalDomicilePlace the value for customers_personal.personal_domicile_place
     *
     * @mbggenerated
     */
    public void setPersonalDomicilePlace(String personalDomicilePlace) {
        this.personalDomicilePlace = personalDomicilePlace == null ? null : personalDomicilePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_nation
     *
     * @return the value of customers_personal.personal_nation
     *
     * @mbggenerated
     */
    public String getPersonalNation() {
        return personalNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_nation
     *
     * @param personalNation the value for customers_personal.personal_nation
     *
     * @mbggenerated
     */
    public void setPersonalNation(String personalNation) {
        this.personalNation = personalNation == null ? null : personalNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_politics_status
     *
     * @return the value of customers_personal.personal_politics_status
     *
     * @mbggenerated
     */
    public String getPersonalPoliticsStatus() {
        return personalPoliticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_politics_status
     *
     * @param personalPoliticsStatus the value for customers_personal.personal_politics_status
     *
     * @mbggenerated
     */
    public void setPersonalPoliticsStatus(String personalPoliticsStatus) {
        this.personalPoliticsStatus = personalPoliticsStatus == null ? null : personalPoliticsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_current_place
     *
     * @return the value of customers_personal.personal_current_place
     *
     * @mbggenerated
     */
    public String getPersonalCurrentPlace() {
        return personalCurrentPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_current_place
     *
     * @param personalCurrentPlace the value for customers_personal.personal_current_place
     *
     * @mbggenerated
     */
    public void setPersonalCurrentPlace(String personalCurrentPlace) {
        this.personalCurrentPlace = personalCurrentPlace == null ? null : personalCurrentPlace.trim();
    }

    public Integer getPersonalEducationHigh() {
        return personalEducationHigh;
    }

    public void setPersonalEducationHigh(Integer personalEducationHigh) {
        this.personalEducationHigh = personalEducationHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_graduate_school
     *
     * @return the value of customers_personal.personal_graduate_school
     *
     * @mbggenerated
     */
    public String getPersonalGraduateSchool() {
        return personalGraduateSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_graduate_school
     *
     * @param personalGraduateSchool the value for customers_personal.personal_graduate_school
     *
     * @mbggenerated
     */
    public void setPersonalGraduateSchool(String personalGraduateSchool) {
        this.personalGraduateSchool = personalGraduateSchool == null ? null : personalGraduateSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_major
     *
     * @return the value of customers_personal.personal_major
     *
     * @mbggenerated
     */
    public String getPersonalMajor() {
        return personalMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_major
     *
     * @param personalMajor the value for customers_personal.personal_major
     *
     * @mbggenerated
     */
    public void setPersonalMajor(String personalMajor) {
        this.personalMajor = personalMajor == null ? null : personalMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_resume
     *
     * @return the value of customers_personal.personal_resume
     *
     * @mbggenerated
     */
    public String getPersonalResume() {
        return personalResume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_resume
     *
     * @param personalResume the value for customers_personal.personal_resume
     *
     * @mbggenerated
     */
    public void setPersonalResume(String personalResume) {
        this.personalResume = personalResume == null ? null : personalResume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_create_time
     *
     * @return the value of customers_personal.personal_create_time
     *
     * @mbggenerated
     */
    public Date getPersonalCreateTime() {
        return personalCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_create_time
     *
     * @param personalCreateTime the value for customers_personal.personal_create_time
     *
     * @mbggenerated
     */
    public void setPersonalCreateTime(Date personalCreateTime) {
        this.personalCreateTime = personalCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers_personal.personal_update_time
     *
     * @return the value of customers_personal.personal_update_time
     *
     * @mbggenerated
     */
    public Date getPersonalUpdateTime() {
        return personalUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers_personal.personal_update_time
     *
     * @param personalUpdateTime the value for customers_personal.personal_update_time
     *
     * @mbggenerated
     */
    public void setPersonalUpdateTime(Date personalUpdateTime) {
        this.personalUpdateTime = personalUpdateTime;
    }
}