package com.xtr.api.domain.customer;

import java.io.Serializable;

public class CustomerShebaoOrderDescBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.company_shebao_order_id
     *
     * @mbggenerated
     */
    private Long companyShebaoOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.gjj_hj_text
     *
     * @mbggenerated
     */
    private String gjjHjText;

    private String gjjZyText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.gjj_bj_text
     *
     * @mbggenerated
     */
    private String gjjBjText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.gjj_tj_text
     *
     * @mbggenerated
     */
    private String gjjTjText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.gjj_stop_text
     *
     * @mbggenerated
     */
    private String gjjStopText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.sb_hj_text
     *
     * @mbggenerated
     */

    private String sbZyText;

    private String sbHjText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.sb_bj_text
     *
     * @mbggenerated
     */
    private String sbBjText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.sb_tj_text
     *
     * @mbggenerated
     */
    private String sbTjText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao_order_desc.sb_stop_text
     *
     * @mbggenerated
     */
    private String sbStopText;

    private String orderErrorText;

    //社保异常详情
    private String sbErrorText;
    //公积金异常详情
    private String gjjErrorText;
    //社保失败原因
    private String sbErrorReason;
    //公积金失败原因
    private String gjjErrorReason;

    public String getSbErrorReason() {
        return sbErrorReason;
    }

    public void setSbErrorReason(String sbErrorReason) {
        this.sbErrorReason = sbErrorReason;
    }

    public String getGjjErrorReason() {
        return gjjErrorReason;
    }

    public void setGjjErrorReason(String gjjErrorReason) {
        this.gjjErrorReason = gjjErrorReason;
    }

    public String getSbErrorText() {
        return sbErrorText;
    }

    public void setSbErrorText(String sbErrorText) {
        this.sbErrorText = sbErrorText;
    }

    public String getGjjErrorText() {
        return gjjErrorText;
    }

    public void setGjjErrorText(String gjjErrorText) {
        this.gjjErrorText = gjjErrorText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.id
     *
     * @return the value of customer_shebao_order_desc.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.id
     *
     * @param id the value for customer_shebao_order_desc.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.company_shebao_order_id
     *
     * @return the value of customer_shebao_order_desc.company_shebao_order_id
     *
     * @mbggenerated
     */
    public Long getCompanyShebaoOrderId() {
        return companyShebaoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.company_shebao_order_id
     *
     * @param companyShebaoOrderId the value for customer_shebao_order_desc.company_shebao_order_id
     *
     * @mbggenerated
     */
    public void setCompanyShebaoOrderId(Long companyShebaoOrderId) {
        this.companyShebaoOrderId = companyShebaoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.customer_id
     *
     * @return the value of customer_shebao_order_desc.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.customer_id
     *
     * @param customerId the value for customer_shebao_order_desc.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.gjj_hj_text
     *
     * @return the value of customer_shebao_order_desc.gjj_hj_text
     *
     * @mbggenerated
     */
    public String getGjjHjText() {
        return gjjHjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.gjj_hj_text
     *
     * @param gjjHjText the value for customer_shebao_order_desc.gjj_hj_text
     *
     * @mbggenerated
     */
    public void setGjjHjText(String gjjHjText) {
        this.gjjHjText = gjjHjText == null ? null : gjjHjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.gjj_bj_text
     *
     * @return the value of customer_shebao_order_desc.gjj_bj_text
     *
     * @mbggenerated
     */
    public String getGjjBjText() {
        return gjjBjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.gjj_bj_text
     *
     * @param gjjBjText the value for customer_shebao_order_desc.gjj_bj_text
     *
     * @mbggenerated
     */
    public void setGjjBjText(String gjjBjText) {
        this.gjjBjText = gjjBjText == null ? null : gjjBjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.gjj_tj_text
     *
     * @return the value of customer_shebao_order_desc.gjj_tj_text
     *
     * @mbggenerated
     */
    public String getGjjTjText() {
        return gjjTjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.gjj_tj_text
     *
     * @param gjjTjText the value for customer_shebao_order_desc.gjj_tj_text
     *
     * @mbggenerated
     */
    public void setGjjTjText(String gjjTjText) {
        this.gjjTjText = gjjTjText == null ? null : gjjTjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.gjj_stop_text
     *
     * @return the value of customer_shebao_order_desc.gjj_stop_text
     *
     * @mbggenerated
     */
    public String getGjjStopText() {
        return gjjStopText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.gjj_stop_text
     *
     * @param gjjStopText the value for customer_shebao_order_desc.gjj_stop_text
     *
     * @mbggenerated
     */
    public void setGjjStopText(String gjjStopText) {
        this.gjjStopText = gjjStopText == null ? null : gjjStopText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.sb_hj_text
     *
     * @return the value of customer_shebao_order_desc.sb_hj_text
     *
     * @mbggenerated
     */
    public String getSbHjText() {
        return sbHjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.sb_hj_text
     *
     * @param sbHjText the value for customer_shebao_order_desc.sb_hj_text
     *
     * @mbggenerated
     */
    public void setSbHjText(String sbHjText) {
        this.sbHjText = sbHjText == null ? null : sbHjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.sb_bj_text
     *
     * @return the value of customer_shebao_order_desc.sb_bj_text
     *
     * @mbggenerated
     */
    public String getSbBjText() {
        return sbBjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.sb_bj_text
     *
     * @param sbBjText the value for customer_shebao_order_desc.sb_bj_text
     *
     * @mbggenerated
     */
    public void setSbBjText(String sbBjText) {
        this.sbBjText = sbBjText == null ? null : sbBjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.sb_tj_text
     *
     * @return the value of customer_shebao_order_desc.sb_tj_text
     *
     * @mbggenerated
     */
    public String getSbTjText() {
        return sbTjText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.sb_tj_text
     *
     * @param sbTjText the value for customer_shebao_order_desc.sb_tj_text
     *
     * @mbggenerated
     */
    public void setSbTjText(String sbTjText) {
        this.sbTjText = sbTjText == null ? null : sbTjText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao_order_desc.sb_stop_text
     *
     * @return the value of customer_shebao_order_desc.sb_stop_text
     *
     * @mbggenerated
     */
    public String getSbStopText() {
        return sbStopText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao_order_desc.sb_stop_text
     *
     * @param sbStopText the value for customer_shebao_order_desc.sb_stop_text
     *
     * @mbggenerated
     */
    public void setSbStopText(String sbStopText) {
        this.sbStopText = sbStopText == null ? null : sbStopText.trim();
    }

    public String getOrderErrorText() {
        return orderErrorText;
    }

    public void setOrderErrorText(String orderErrorText) {
        this.orderErrorText = orderErrorText;
    }

    public String getGjjZyText() {
        return gjjZyText;
    }

    public void setGjjZyText(String gjjZyText) {
        this.gjjZyText = gjjZyText;
    }

    public String getSbZyText() {
        return sbZyText;
    }

    public void setSbZyText(String sbZyText) {
        this.sbZyText = sbZyText;
    }
}