package com.xtr.api.domain.customer;

import com.xtr.api.basic.BaseObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CustomerShebaoBean extends BaseObject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    private Long currentCompanyOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.join_city_name
     *
     * @mbggenerated
     */
    private String joinCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.join_city_code
     *
     * @mbggenerated
     */
    private String joinCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.sb_type
     *
     * @mbggenerated
     */
    private String sbType;
    private String sbTypeName;


    private String gjjType;
    private String gjjTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.sb_base
     *
     * @mbggenerated
     */
    private BigDecimal sbBase;
    private BigDecimal sbSbtBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.bjj_base
     *
     * @mbggenerated
     */
    private BigDecimal gjjBase;
    private BigDecimal gjjSbtBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.sb_shebaotong_status
     *
     * @mbggenerated
     */
    private Integer sbShebaotongStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.gjj_shebaotong_status
     *
     * @mbggenerated
     */
    private Integer gjjShebaotongStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.is_sb_keep
     *
     * @mbggenerated
     */
    private Integer isSbKeep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.is_gjj_keep
     *
     * @mbggenerated
     */
    private Integer isGjjKeep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.sb_join_date
     *
     * @mbggenerated
     */
    private Date sbJoinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.gjj_join_date
     *
     * @mbggenerated
     */
    private Date gjjJoinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.sb_stop_date
     *
     * @mbggenerated
     */
    private Date sbStopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.gjj_stop_date
     *
     * @mbggenerated
     */
    private Date currentMonth;

    private Date gjjStopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.response_msg
     *
     * @mbggenerated
     */
    private String responseMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_shebao.create_time
     *
     * @mbggenerated
     */
    private Date createTime;


    private Integer stationCustomerState;

    private Long depId;

    private String userName;

    private String stationEmployMethod;

    private Long companyId;

    //查询条件新入职 社保在缴  公积金在缴 资料审核失败
    private Boolean isNew;

    private Boolean isKeepSb;

    private Boolean isKeepGjj;

    private Boolean isFailed;

    private String depName;

    //判断社保还是公积金 1社保 2公积金
    private Integer isType;

    public Integer getIsType() {
        return isType;
    }

    public void setIsType(Integer isType) {
        this.isType = isType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.id
     *
     * @return the value of customer_shebao.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.id
     *
     * @param id the value for customer_shebao.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.customer_id
     *
     * @return the value of customer_shebao.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.customer_id
     *
     * @param customerId the value for customer_shebao.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.join_city_name
     *
     * @return the value of customer_shebao.join_city_name
     *
     * @mbggenerated
     */
    public String getJoinCityName() {
        return joinCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.join_city_name
     *
     * @param joinCityName the value for customer_shebao.join_city_name
     *
     * @mbggenerated
     */
    public void setJoinCityName(String joinCityName) {
        this.joinCityName = joinCityName == null ? null : joinCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.join_city_code
     *
     * @return the value of customer_shebao.join_city_code
     *
     * @mbggenerated
     */
    public String getJoinCityCode() {
        return joinCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.join_city_code
     *
     * @param joinCityCode the value for customer_shebao.join_city_code
     *
     * @mbggenerated
     */
    public void setJoinCityCode(String joinCityCode) {
        this.joinCityCode = joinCityCode == null ? null : joinCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.sb_type
     *
     * @return the value of customer_shebao.sb_type
     *
     * @mbggenerated
     */
    public String getSbType() {
        return sbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.sb_type
     *
     * @param sbType the value for customer_shebao.sb_type
     *
     * @mbggenerated
     */
    public void setSbType(String sbType) {
        this.sbType = sbType == null ? null : sbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.sb_base
     *
     * @return the value of customer_shebao.sb_base
     *
     * @mbggenerated
     */
    public BigDecimal getSbBase() {
        return sbBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.sb_base
     *
     * @param sbBase the value for customer_shebao.sb_base
     *
     * @mbggenerated
     */
    public void setSbBase(BigDecimal sbBase) {
        this.sbBase = sbBase;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.sb_shebaotong_status
     *
     * @return the value of customer_shebao.sb_shebaotong_status
     *
     * @mbggenerated
     */
    public Integer getSbShebaotongStatus() {
        return sbShebaotongStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.sb_shebaotong_status
     *
     * @param sbShebaotongStatus the value for customer_shebao.sb_shebaotong_status
     *
     * @mbggenerated
     */
    public void setSbShebaotongStatus(Integer sbShebaotongStatus) {
        this.sbShebaotongStatus = sbShebaotongStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.gjj_shebaotong_status
     *
     * @return the value of customer_shebao.gjj_shebaotong_status
     *
     * @mbggenerated
     */
    public Integer getGjjShebaotongStatus() {
        return gjjShebaotongStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.gjj_shebaotong_status
     *
     * @param gjjShebaotongStatus the value for customer_shebao.gjj_shebaotong_status
     *
     * @mbggenerated
     */
    public void setGjjShebaotongStatus(Integer gjjShebaotongStatus) {
        this.gjjShebaotongStatus = gjjShebaotongStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.is_sb_keep
     *
     * @return the value of customer_shebao.is_sb_keep
     *
     * @mbggenerated
     */
    public Integer getIsSbKeep() {
        return isSbKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.is_sb_keep
     *
     * @param isSbKeep the value for customer_shebao.is_sb_keep
     *
     * @mbggenerated
     */
    public void setIsSbKeep(Integer isSbKeep) {
        this.isSbKeep = isSbKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.is_gjj_keep
     *
     * @return the value of customer_shebao.is_gjj_keep
     *
     * @mbggenerated
     */
    public Integer getIsGjjKeep() {
        return isGjjKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.is_gjj_keep
     *
     * @param isGjjKeep the value for customer_shebao.is_gjj_keep
     *
     * @mbggenerated
     */
    public void setIsGjjKeep(Integer isGjjKeep) {
        this.isGjjKeep = isGjjKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.sb_join_date
     *
     * @return the value of customer_shebao.sb_join_date
     *
     * @mbggenerated
     */
    public Date getSbJoinDate() {
        return sbJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.sb_join_date
     *
     * @param sbJoinDate the value for customer_shebao.sb_join_date
     *
     * @mbggenerated
     */
    public void setSbJoinDate(Date sbJoinDate) {
        this.sbJoinDate = sbJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.gjj_join_date
     *
     * @return the value of customer_shebao.gjj_join_date
     *
     * @mbggenerated
     */
    public Date getGjjJoinDate() {
        return gjjJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.gjj_join_date
     *
     * @param gjjJoinDate the value for customer_shebao.gjj_join_date
     *
     * @mbggenerated
     */
    public void setGjjJoinDate(Date gjjJoinDate) {
        this.gjjJoinDate = gjjJoinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.sb_stop_date
     *
     * @return the value of customer_shebao.sb_stop_date
     *
     * @mbggenerated
     */
    public Date getSbStopDate() {
        return sbStopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.sb_stop_date
     *
     * @param sbStopDate the value for customer_shebao.sb_stop_date
     *
     * @mbggenerated
     */
    public void setSbStopDate(Date sbStopDate) {
        this.sbStopDate = sbStopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.gjj_stop_date
     *
     * @return the value of customer_shebao.gjj_stop_date
     *
     * @mbggenerated
     */
    public Date getGjjStopDate() {
        return gjjStopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.gjj_stop_date
     *
     * @param gjjStopDate the value for customer_shebao.gjj_stop_date
     *
     * @mbggenerated
     */
    public void setGjjStopDate(Date gjjStopDate) {
        this.gjjStopDate = gjjStopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.response_msg
     *
     * @return the value of customer_shebao.response_msg
     *
     * @mbggenerated
     */
    public String getResponseMsg() {
        return responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.response_msg
     *
     * @param responseMsg the value for customer_shebao.response_msg
     *
     * @mbggenerated
     */
    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg == null ? null : responseMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_shebao.create_time
     *
     * @return the value of customer_shebao.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_shebao.create_time
     *
     * @param createTime the value for customer_shebao.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getStationCustomerState() {
        return stationCustomerState;
    }

    public void setStationCustomerState(Integer stationCustomerState) {
        this.stationCustomerState = stationCustomerState;
    }

    public Long getDepId() {
        return depId;
    }

    public void setDepId(Long depId) {
        this.depId = depId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getStationEmployMethod() {
        return stationEmployMethod;
    }

    public void setStationEmployMethod(String stationEmployMethod) {
        this.stationEmployMethod = stationEmployMethod;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getGjjType() {
        return gjjType;
    }

    public void setGjjType(String gjjType) {
        this.gjjType = gjjType;
    }

    public BigDecimal getGjjBase() {
        return gjjBase;
    }

    public void setGjjBase(BigDecimal gjjBase) {
        this.gjjBase = gjjBase;
    }

    public Date getCurrentMonth() {
        return currentMonth;
    }

    public void setCurrentMonth(Date currentMonth) {
        this.currentMonth = currentMonth;
    }

    public Long getCurrentCompanyOrderId() {
        return currentCompanyOrderId;
    }

    public void setCurrentCompanyOrderId(Long currentCompanyOrderId) {
        this.currentCompanyOrderId = currentCompanyOrderId;
    }

    public String getSbTypeName() {
        return sbTypeName;
    }

    public void setSbTypeName(String sbTypeName) {
        this.sbTypeName = sbTypeName;
    }

    public String getGjjTypeName() {
        return gjjTypeName;
    }

    public void setGjjTypeName(String gjjTypeName) {
        this.gjjTypeName = gjjTypeName;
    }

    public Boolean getIsNew() {
        return isNew;
    }

    public void setIsNew(Boolean aNew) {
        isNew = aNew;
    }

    public Boolean getIsKeepSb() {
        return isKeepSb;
    }

    public void setIsKeepSb(Boolean keepSb) {
        isKeepSb = keepSb;
    }

    public Boolean getIsKeepGjj() {
        return isKeepGjj;
    }

    public void setIsKeepGjj(Boolean keepGjj) {
        isKeepGjj = keepGjj;
    }

    public Boolean getIsFailed() {
        return isFailed;
    }

    public void setIsFailed(Boolean failed) {
        isFailed = failed;
    }

    public String getDepName() {
        return depName;
    }

    public void setDepName(String depName) {
        this.depName = depName;
    }

    public BigDecimal getSbSbtBase() {
        return sbSbtBase;
    }

    public void setSbSbtBase(BigDecimal sbSbtBase) {
        this.sbSbtBase = sbSbtBase;
    }

    public BigDecimal getGjjSbtBase() {
        return gjjSbtBase;
    }

    public void setGjjSbtBase(BigDecimal gjjSbtBase) {
        this.gjjSbtBase = gjjSbtBase;
    }
}