package com.xtr.api.domain.customer;

public class LegalHolidayBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_holiday.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_holiday.month
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_holiday.legal_holiday
     *
     * @mbggenerated
     */
    private String legalHoliday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_holiday.year
     *
     * @return the value of legal_holiday.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_holiday.year
     *
     * @param year the value for legal_holiday.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_holiday.month
     *
     * @return the value of legal_holiday.month
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_holiday.month
     *
     * @param month the value for legal_holiday.month
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_holiday.legal_holiday
     *
     * @return the value of legal_holiday.legal_holiday
     *
     * @mbggenerated
     */
    public String getLegalHoliday() {
        return legalHoliday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_holiday.legal_holiday
     *
     * @param legalHoliday the value for legal_holiday.legal_holiday
     *
     * @mbggenerated
     */
    public void setLegalHoliday(String legalHoliday) {
        this.legalHoliday = legalHoliday == null ? null : legalHoliday.trim();
    }
}