package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.CustomersStationBean;
import org.apache.ibatis.annotations.Param;
import com.xtr.api.dto.customer.CustomersDto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface CustomersStationWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long stationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int insert(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int insertSelective(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomersStationBean record);

    /**
     * 根据用户id更新岗位信息
     * @param customersStationBean
     * @return
     */
    int updateByCustomerId(CustomersStationBean customersStationBean);
    /**
     * 更新员工部门
     * @param depId
     * @param empId
     * @return
     */
    int updateDept(@Param("depId") Long depId, @Param("empId")long empId);
    /**
     * 更新员工岗位信息为删除
     *
     * @return
     */
    int updateCustomerStateByCustomerId(CustomersStationBean co);


    /**
     * 跟新员工状态为转正
     * @param cus
     * @return
     */
    int updateStateByCustomerId(CustomersStationBean cus);

    /**
     * 批量插入员工岗位信息
     * @param list
     * @return
     */
    int insertBatch(List<CustomersStationBean> list);
}