package com.xtr.core.persistence.writer.customer;


import com.xtr.api.domain.customer.CustomerRechargesBean;
import org.apache.ibatis.annotations.Param;

public interface CustomerRechargesWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int insert(CustomerRechargesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int insertSelective(CustomerRechargesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerRechargesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerRechargesBean record);

    /**
     * 根据企业id删除
     *
     * @param companyId
     */
    void deleteByCompanyId(@Param("companyId") Long companyId);
}