package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.CustomerExpenseDetailBean;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;

public interface CustomerExpenseDetailWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    int insert(CustomerExpenseDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    int insertSelective(CustomerExpenseDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerExpenseDetailBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerExpenseDetailBean record);

    /**
     * 批量调额
     * @param companyId
     * @param gt
     * @param lt
     * @param bl
     * @return
     */
    int batchUpdateExpense(@Param("companyId") long companyId, @Param("bgt") BigDecimal gt, @Param("blt") BigDecimal lt, @Param("bbl") Float bl);

    /**
     * 根据ID集合删除
     * @param ids
     * @return
     */
    int deleteByIds(@Param("deleteIds") String ids);

    /**
     * 更新所有员工的定额状态
     */
    int updateExpenseStatus();


    /**
     * 批量更新工资单状态为 规则已改动
     * @param companyId
     * @param gt
     * @param lt
     */
    void updatePayRollStatusByBatch(@Param("companyId") long companyId, @Param("cycleId") long cycleId, @Param("bgt") BigDecimal gt, @Param("blt") BigDecimal lt);
}