package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.CustomerShebaoBean;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface CustomerShebaoWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    int insert(CustomerShebaoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    int insertSelective(CustomerShebaoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerShebaoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerShebaoBean record);

    /**
     * 更新员工当前缴纳月
     * @param companyId
     * @param cityCode
     * @param orderDate
     */
    void updateCurrentMonth(@Param("companyId") long companyId, @Param("cityCode") String cityCode, @Param("orderDate") Date orderDate, @Param("orderId") Long orderId);

    /**
     * 批量插入员工社保公积金基本信息
     * @param list
     * @return
     */
    int insertBatch(List<CustomerShebaoBean> list);

    /**
     * 批量更新员工社保公积金基本信息
     * @param list
     * @return
     */
    int updateBatch(List<CustomerShebaoBean> list);

    /**
     * 批量更新员工公积金社保的社保通返回状态
     * @param type
     * @param status
     * @param companyShebaoOrderId
     * @param list
     * @return
     */
    int updateSbAndGjjStateBatch(@Param("type") int type, @Param("status") int status, @Param("companyShebaoOrderId") long companyShebaoOrderId,@Param("list") List<Long> list);

    /**
     * 根据条件更新员工社保公积金的社保通状态
     * @param type
     * @param record
     * @return
     */
    int updateSbAndGjjStateByCondition(@Param("type") int type,@Param("record") CustomerShebaoBean record);


    /**
     * 更新社保错误信息
     * @param customerId
     * @param errorMsg
     * @param sbIsOk
     *@param gjjIsOk @return
     */
    int updateErrorMsg(@Param("customerId") Long customerId, @Param("errorMsg") String errorMsg, @Param("sbIsOk") boolean sbIsOk, @Param("gjjIsOk") boolean gjjIsOk);

    /**
     * 更新社保通状态
     * @param customerId
     * @param type
     * @param status
     * @return
     */
    int updateSbtStatus(@Param("customerId") Long customerId, @Param("sbtype") int type, @Param("sbstatus") int status);

    /**
     * 维护员工社保表的当前缴纳月份和当前企业订单
     * @return
     */
    int upToDateCurrent();

    /**
     * 更新社保状态
     * @param companyId
     * @param joinCity
     * @param requireType
     * @param orderDate
     * @return
     */
    int updateStopCustomer(@Param("companyId") long companyId, @Param("joinCity") String joinCity, @Param("requireType") int requireType, @Param("orderDate")Date orderDate);

    /**
     * 清空停缴日期
     * @param type
     * @return
     */
    int updateForStopDate(@Param("type") int type, @Param("currentCompanyOrderId") long currentCompanyOrderId, @Param("customerId") long customerId);

    /**
     * 取消停缴更新数据
     * @param type
     * @param record
     * @return
     */
    int updateForStopDateCondition(@Param("type") int type, @Param("customerShebaoBean") CustomerShebaoBean record);

    /**
     * 批量更新社保通状态
     * @param type
     * @param shebaotongStatus
     * @param list
     * @return
     */
    int updateSbAndGjjStateByConditionBatch(@Param("type") int type, @Param("shebaotongStatus") int shebaotongStatus,@Param("currentCompanyOrderId") long currentCompanyOrderId,@Param("list") List<CustomerShebaoBean> list);

    /**
     *批量更新员工社保公积金的社保通状态
     * @param list
     * @return
     */
    int updateSbAndGjjStateByConditionForBatch(@Param("list") List<CustomerShebaoBean> list);
}