package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.CustomersRecordBean;

import java.util.Date;
import java.util.List;

public interface CustomersRecordWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    int insert(CustomersRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    int insertSelective(CustomersRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomersRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomersRecordBean record);

    /**
     * 根据用户id更新数据
     * @param customersRecordBean
     * @return
     */
    int updateByCustomerId(CustomersRecordBean customersRecordBean);

    /**
     * 批量插入员工记录信息
     * @param list
     * @return
     */
    int insertBatch(List<CustomersRecordBean> list);
}