package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.CustomersPersonalBean;

public interface CustomersPersonalWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long personalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int insert(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int insertSelective(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomersPersonalBean record);
}