package com.xtr.core.persistence.writer.customer;

import com.xtr.api.domain.customer.LegalHolidayBean;

public interface LegalHolidayWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_holiday
     *
     * @mbggenerated
     */
    int insert(LegalHolidayBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_holiday
     *
     * @mbggenerated
     */
    int insertSelective(LegalHolidayBean record);
}