package com.xtr.api.domain.gateway;

import java.io.Serializable;
import java.util.Date;

public class GatewayLogBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.log_type
     *
     * @mbggenerated
     */
    private Integer logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.log_content
     *
     * @mbggenerated
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.business_type
     *
     * @mbggenerated
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.business_id
     *
     * @mbggenerated
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.log_date
     *
     * @mbggenerated
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_log.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.id
     *
     * @return the value of gateway_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.id
     *
     * @param id the value for gateway_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.log_type
     *
     * @return the value of gateway_log.log_type
     *
     * @mbggenerated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.log_type
     *
     * @param logType the value for gateway_log.log_type
     *
     * @mbggenerated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.log_content
     *
     * @return the value of gateway_log.log_content
     *
     * @mbggenerated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.log_content
     *
     * @param logContent the value for gateway_log.log_content
     *
     * @mbggenerated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.business_type
     *
     * @return the value of gateway_log.business_type
     *
     * @mbggenerated
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.business_type
     *
     * @param businessType the value for gateway_log.business_type
     *
     * @mbggenerated
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.business_id
     *
     * @return the value of gateway_log.business_id
     *
     * @mbggenerated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.business_id
     *
     * @param businessId the value for gateway_log.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.log_date
     *
     * @return the value of gateway_log.log_date
     *
     * @mbggenerated
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.log_date
     *
     * @param logDate the value for gateway_log.log_date
     *
     * @mbggenerated
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_log.api_name
     *
     * @return the value of gateway_log.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_log.api_name
     *
     * @param apiName the value for gateway_log.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }
}