package com.xtr.core.persistence.reader.company;

import com.xtr.api.domain.company.CompanyMsgsBean;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CompanyMsgsReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    CompanyMsgsBean selectByPrimaryKey(Long msgId);

    /**
     * 查询所有未读消息
     * @param companyId
     * @return
     */
    List<CompanyMsgsBean> selectAllUnReadMsg(@Param("cId") long companyId, @Param("maxSize")long maxSize);

    /**
     * 查询当前用户的未读消息
     * @param msgCompanyId
     * @return
     */
    List<CompanyMsgsBean> findCompanyMsgsBeanListByCompanyId(Long msgCompanyId);

    /**
     * 查询当前公司用户的未读消息个数
     * @param memberCompanyId
     * @return
     */
    long getUnReadCounts(Long memberCompanyId);

    /**
     * 根据主键查询没有被删除的消息
     * @param msgId
     * @return
     */
    CompanyMsgsBean selectNoDelete(Long msgId);

    /**
     * 新版消息盒子 查询已读 或者 未读消息
     * @param companyId
     * @param msgSign
     * @return
     */
    List<CompanyMsgsBean> selectCompanyMsgs(@Param("companyId") Long companyId, @Param("msgSign") Integer msgSign);
}