package com.xtr.core.persistence.reader.company;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.xtr.api.domain.company.CompanyNotesBean;
import org.apache.ibatis.annotations.Param;

public interface CompanyNotesReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    CompanyNotesBean selectByPrimaryKey(Long noteId);


    PageList<CompanyNotesBean> selectPage(@Param("cId")Long cId, PageBounds pageBounds);
}