package com.xtr.core.persistence.writer.gateway;

import com.xtr.api.domain.gateway.GatewayLogBean;

public interface GatewayLogWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int insert(GatewayLogBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int insertWithLock(GatewayLogBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int insertSelective(GatewayLogBean record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatewayLogBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GatewayLogBean record);
}