package com.xtr.core.persistence.writer.app;

import com.xtr.api.domain.app.AppQuestionFeedbackBean;

public interface AppQuestionFeedbackWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    int insert(AppQuestionFeedbackBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    int insertSelective(AppQuestionFeedbackBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppQuestionFeedbackBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppQuestionFeedbackBean record);
}