package com.xtr.api.dto.customer;

import com.xtr.api.domain.customer.CustomersBean;

import java.io.InputStream;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author 王志新 robert.wang@xintairuan.com
 * @createTime:2016/7/8 11:19
 */
public class CustomersDto extends CustomersBean implements Serializable {

    //账户余额
    private BigDecimal totalAmount;
    private Long stationId;


    private Long stationCustomerId;


    private Date stationEnterTime;


    private Integer stationEmployMethod;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_regular_time
     *
     * @mbggenerated
     */
    private Date stationRegularTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_customer_number
     *
     * @mbggenerated
     */
    private String stationCustomerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_customer_state
     *
     * @mbggenerated
     */
    private Integer stationCustomerState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_dept_id
     *
     * @mbggenerated
     */
    private Long stationDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_station_name
     *
     * @mbggenerated
     */
    private String stationStationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_contract_file
     *
     * @mbggenerated
     */
    private String stationContractFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_regular_evaluate
     *
     * @mbggenerated
     */
    private String stationRegularEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_create_time
     *
     * @mbggenerated
     */
    private Date stationCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_station.station_update_time
     *
     * @mbggenerated
     */
    private Date stationUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_id
     *
     * @mbggenerated
     */
    private Long personalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_customer_id
     *
     * @mbggenerated
     */
    private Long personalCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_relationer_name
     *
     * @mbggenerated
     */
    private String personalRelationerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_relationer_phone
     *
     * @mbggenerated
     */
    private String personalRelationerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_domicile_place
     *
     * @mbggenerated
     */
    private String personalDomicilePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_nation
     *
     * @mbggenerated
     */
    private String personalNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_politics_status
     *
     * @mbggenerated
     */
    private String personalPoliticsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_current_place
     *
     * @mbggenerated
     */
    private String personalCurrentPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_education_high
     *
     * @mbggenerated
     */
    private Integer personalEducationHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_graduate_school
     *
     * @mbggenerated
     */
    private String personalGraduateSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_major
     *
     * @mbggenerated
     */
    private String personalMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_resume
     *
     * @mbggenerated
     */
    private String personalResume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_create_time
     *
     * @mbggenerated
     */
    private Date personalCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_personal.personal_update_time
     *
     * @mbggenerated
     */
    private Date personalUpdateTime;

    /**
     * id,所属表字段为company_deps.dep_id
     */
    private Long depId;

    /**
     * 所属企业id,所属表字段为company_deps.dep_company_id
     */
    private Long depCompanyId;

    /**
     * 上级id,所属表字段为company_deps.dep_parent_id
     */
    private Long depParentId;

    /**
     * 本门名称,所属表字段为company_deps.dep_name
     */
    private String depName;

    /**
     * 部门编号,所属表字段为company_deps.dep_number
     */
    private String depNumber;

    /**
     * 1总公司(集团) 2部门 3子公司,所属表字段为company_deps.dep_type
     */
    private Integer depType;

    /**
     * 发薪日 0未设置,所属表字段为company_deps.dep_salary_day
     */
    private Integer depSalaryDay;

    /**
     * 状态 0禁用 1可用,所属表字段为company_deps.dep_sign
     */
    private Integer depSign;

    /**
     * 薪资计算周期,所属表字段为company_deps.dep_salary_sumdays
     */
    private Integer depSalarySumdays;

    /**
     * 员工上传日,所属表字段为company_deps.dep_updateuser_date
     */
    private Integer depUpdateuserDate;

    /**
     * 修改人,所属表字段为company_deps.dep_edit_member
     */
    private Long depEditMember;

    /**
     * 修改时间,所属表字段为company_deps.dep_edit_time
     */
    private Date depEditTime;

    /**
     * 企业id,所属表字段为company_deps.company_id
     */
    private Long companyId;

    /**
     * 所属层级 1 开始,所属表字段为company_deps.dep_level
     */
    private Integer depLevel;

    //起始日期
    private Date startTime;
    //结束日期
    private Date endTime;
    //查询状态 1入职 2离职 3待转正 4未补全资料
    private Integer selState;
    //离职日期
    private Date stationDimissingTime;
    //调岗前部门名称
    private String beforeDepName;
    //调岗后部门名称
    private String afterDepName;
    //操作状态 1新增 2编辑 3重复
    private Integer willOperationState;

    public Integer getWillOperationState() {
        return willOperationState;
    }

    public void setWillOperationState(Integer willOperationState) {
        this.willOperationState = willOperationState;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_id
     *
     * @mbggenerated
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_customer_id
     *
     * @mbggenerated
     */
    private Long recordCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_operation_type
     *
     * @mbggenerated
     */
    private Integer recordOperationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_operation_time
     *
     * @mbggenerated
     */
    private Date recordOperationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dept_id
     *
     * @mbggenerated
     */
    private Long recordDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dept_name
     *
     * @mbggenerated
     */
    private String recordDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dimissing_time
     *
     * @mbggenerated
     */
    private Date recordDimissingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_dimissing_reason
     *
     * @mbggenerated
     */
    private String recordDimissingReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers_record.record_create_time
     *
     * @mbggenerated
     */
    private Date recordCreateTime;

    //调岗前部门ID
    private Long recordDeptIdBefore;
    //调岗前岗位
    private String recordStationNameBefore;
    //调岗后岗位
    private String recordStationNameAfter;
    //调薪前工资
    private BigDecimal recordSalaryBefore;
    //调薪后工资
    private BigDecimal recordSalaryAfter;
    //是否待离职 1是 2否
    private Integer willLeaveState;
    //首页显示员工的类型 1全部 2正式 3试用期 4即将离职 5已离职
    private Integer showIndexType;
    //津贴方案
    private String allowanceWay;
    //最新基本工资
    private BigDecimal currentSalary;
    //入职时间排序1正序 2倒序
    private Integer  isSortEnterTime;

    public Integer getIsSortEnterTime() {
        return isSortEnterTime;
    }

    public void setIsSortEnterTime(Integer isSortEnterTime) {
        this.isSortEnterTime = isSortEnterTime;
    }

    public BigDecimal getCurrentSalary() {
        return currentSalary;
    }

    public void setCurrentSalary(BigDecimal currentSalary) {
        this.currentSalary = currentSalary;
    }

    public String getAllowanceWay() {
        return allowanceWay;
    }

    public void setAllowanceWay(String allowanceWay) {
        this.allowanceWay = allowanceWay;
    }

    public Integer getShowIndexType() {
        return showIndexType;
    }

    public void setShowIndexType(Integer showIndexType) {
        this.showIndexType = showIndexType;
    }

    public Integer getWillLeaveState() {
        return willLeaveState;
    }

    public void setWillLeaveState(Integer willLeaveState) {
        this.willLeaveState = willLeaveState;
    }

    public String getBeforeDepName() {
        return beforeDepName;
    }

    public void setBeforeDepName(String beforeDepName) {
        this.beforeDepName = beforeDepName;
    }

    public String getAfterDepName() {
        return afterDepName;
    }

    public void setAfterDepName(String afterDepName) {
        this.afterDepName = afterDepName;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Long getStationId() {
        return stationId;
    }

    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    public Long getStationCustomerId() {
        return stationCustomerId;
    }

    public void setStationCustomerId(Long stationCustomerId) {
        this.stationCustomerId = stationCustomerId;
    }

    public Date getStationEnterTime() {
        return stationEnterTime;
    }

    public void setStationEnterTime(Date stationEnterTime) {
        this.stationEnterTime = stationEnterTime;
    }

    public Integer getStationEmployMethod() {
        return stationEmployMethod;
    }

    public void setStationEmployMethod(Integer stationEmployMethod) {
        this.stationEmployMethod = stationEmployMethod;
    }

    public Date getStationRegularTime() {
        return stationRegularTime;
    }

    public void setStationRegularTime(Date stationRegularTime) {
        this.stationRegularTime = stationRegularTime;
    }

    public String getStationCustomerNumber() {
        return stationCustomerNumber;
    }

    public void setStationCustomerNumber(String stationCustomerNumber) {
        this.stationCustomerNumber = stationCustomerNumber;
    }

    public Integer getStationCustomerState() {
        return stationCustomerState;
    }

    public void setStationCustomerState(Integer stationCustomerState) {
        this.stationCustomerState = stationCustomerState;
    }

    public Long getStationDeptId() {
        return stationDeptId;
    }

    public void setStationDeptId(Long stationDeptId) {
        this.stationDeptId = stationDeptId;
    }

    public String getStationStationName() {
        return stationStationName;
    }

    public void setStationStationName(String stationStationName) {
        this.stationStationName = stationStationName;
    }

    public String getStationContractFile() {
        return stationContractFile;
    }

    public void setStationContractFile(String stationContractFile) {
        this.stationContractFile = stationContractFile;
    }

    public String getStationRegularEvaluate() {
        return stationRegularEvaluate;
    }

    public void setStationRegularEvaluate(String stationRegularEvaluate) {
        this.stationRegularEvaluate = stationRegularEvaluate;
    }

    public Date getStationCreateTime() {
        return stationCreateTime;
    }

    public void setStationCreateTime(Date stationCreateTime) {
        this.stationCreateTime = stationCreateTime;
    }

    public Date getStationUpdateTime() {
        return stationUpdateTime;
    }

    public void setStationUpdateTime(Date stationUpdateTime) {
        this.stationUpdateTime = stationUpdateTime;
    }

    public Long getPersonalId() {
        return personalId;
    }

    public void setPersonalId(Long personalId) {
        this.personalId = personalId;
    }

    public Long getPersonalCustomerId() {
        return personalCustomerId;
    }

    public void setPersonalCustomerId(Long personalCustomerId) {
        this.personalCustomerId = personalCustomerId;
    }

    public String getPersonalRelationerName() {
        return personalRelationerName;
    }

    public void setPersonalRelationerName(String personalRelationerName) {
        this.personalRelationerName = personalRelationerName;
    }

    public String getPersonalRelationerPhone() {
        return personalRelationerPhone;
    }

    public void setPersonalRelationerPhone(String personalRelationerPhone) {
        this.personalRelationerPhone = personalRelationerPhone;
    }

    public String getPersonalDomicilePlace() {
        return personalDomicilePlace;
    }

    public void setPersonalDomicilePlace(String personalDomicilePlace) {
        this.personalDomicilePlace = personalDomicilePlace;
    }

    public String getPersonalNation() {
        return personalNation;
    }

    public void setPersonalNation(String personalNation) {
        this.personalNation = personalNation;
    }

    public String getPersonalPoliticsStatus() {
        return personalPoliticsStatus;
    }

    public void setPersonalPoliticsStatus(String personalPoliticsStatus) {
        this.personalPoliticsStatus = personalPoliticsStatus;
    }

    public String getPersonalCurrentPlace() {
        return personalCurrentPlace;
    }

    public void setPersonalCurrentPlace(String personalCurrentPlace) {
        this.personalCurrentPlace = personalCurrentPlace;
    }

    public Integer getPersonalEducationHigh() {
        return personalEducationHigh;
    }

    public void setPersonalEducationHigh(Integer personalEducationHigh) {
        this.personalEducationHigh = personalEducationHigh;
    }

    public String getPersonalGraduateSchool() {
        return personalGraduateSchool;
    }

    public void setPersonalGraduateSchool(String personalGraduateSchool) {
        this.personalGraduateSchool = personalGraduateSchool;
    }

    public String getPersonalMajor() {
        return personalMajor;
    }

    public void setPersonalMajor(String personalMajor) {
        this.personalMajor = personalMajor;
    }

    public String getPersonalResume() {
        return personalResume;
    }

    public void setPersonalResume(String personalResume) {
        this.personalResume = personalResume;
    }

    public Date getPersonalCreateTime() {
        return personalCreateTime;
    }

    public void setPersonalCreateTime(Date personalCreateTime) {
        this.personalCreateTime = personalCreateTime;
    }

    public Date getPersonalUpdateTime() {
        return personalUpdateTime;
    }

    public void setPersonalUpdateTime(Date personalUpdateTime) {
        this.personalUpdateTime = personalUpdateTime;
    }

    public Long getDepId() {
        return depId;
    }

    public void setDepId(Long depId) {
        this.depId = depId;
    }

    public Long getDepCompanyId() {
        return depCompanyId;
    }

    public void setDepCompanyId(Long depCompanyId) {
        this.depCompanyId = depCompanyId;
    }

    public Long getDepParentId() {
        return depParentId;
    }

    public void setDepParentId(Long depParentId) {
        this.depParentId = depParentId;
    }

    public String getDepName() {
        return depName;
    }

    public void setDepName(String depName) {
        this.depName = depName;
    }

    public String getDepNumber() {
        return depNumber;
    }

    public void setDepNumber(String depNumber) {
        this.depNumber = depNumber;
    }

    public Integer getDepType() {
        return depType;
    }

    public void setDepType(Integer depType) {
        this.depType = depType;
    }

    public Integer getDepSalaryDay() {
        return depSalaryDay;
    }

    public void setDepSalaryDay(Integer depSalaryDay) {
        this.depSalaryDay = depSalaryDay;
    }

    public Integer getDepSign() {
        return depSign;
    }

    public void setDepSign(Integer depSign) {
        this.depSign = depSign;
    }

    public Integer getDepSalarySumdays() {
        return depSalarySumdays;
    }

    public void setDepSalarySumdays(Integer depSalarySumdays) {
        this.depSalarySumdays = depSalarySumdays;
    }

    public Integer getDepUpdateuserDate() {
        return depUpdateuserDate;
    }

    public void setDepUpdateuserDate(Integer depUpdateuserDate) {
        this.depUpdateuserDate = depUpdateuserDate;
    }

    public Long getDepEditMember() {
        return depEditMember;
    }

    public void setDepEditMember(Long depEditMember) {
        this.depEditMember = depEditMember;
    }

    public Date getDepEditTime() {
        return depEditTime;
    }

    public void setDepEditTime(Date depEditTime) {
        this.depEditTime = depEditTime;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Integer getDepLevel() {
        return depLevel;
    }

    public void setDepLevel(Integer depLevel) {
        this.depLevel = depLevel;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Integer getSelState() {
        return selState;
    }

    public void setSelState(Integer selState) {
        this.selState = selState;
    }

    public Date getStationDimissingTime() {
        return stationDimissingTime;
    }

    //是否转正  转正标识位：2
    private Integer isRegular;
    //到岗时间
    private Date recordArriveTime;

    public String getRecordStationReason() {
        return recordStationReason;
    }

    public void setRecordStationReason(String recordStationReason) {
        this.recordStationReason = recordStationReason;
    }

    public Date getRecordUpdateTime() {
        return recordUpdateTime;
    }

    public void setRecordUpdateTime(Date recordUpdateTime) {
        this.recordUpdateTime = recordUpdateTime;
    }

    //调岗原因
    private String recordStationReason;
    //更新时间
    private Date recordUpdateTime;
    //离职类型
    private Integer recordDimissingType;//1：主动离职  2：被动离职
    //补偿金
    private BigDecimal recordCompensation;
    //离职原因
    private String dimissingReason;

    //返回当前年的月份
    private String month;
    //返回改年该月的在职人数
    private Long peopleCount;

    private String year;

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Long getPeopleCount() {
        return peopleCount;
    }

    public void setPeopleCount(Long peopleCount) {
        this.peopleCount = peopleCount;
    }

    public String getDimissingReason() {
        return dimissingReason;
    }

    public void setDimissingReason(String dimissingReason) {
        this.dimissingReason = dimissingReason;
    }

    public BigDecimal getRecordCompensation() {
        return recordCompensation;
    }

    public void setRecordCompensation(BigDecimal recordCompensation) {
        this.recordCompensation = recordCompensation;
    }

    public Integer getRecordDimissingType() {
        return recordDimissingType;
    }

    public void setRecordDimissingType(Integer recordDimissingType) {
        this.recordDimissingType = recordDimissingType;
    }

    public Date getRecordArriveTime() {
        return recordArriveTime;
    }

    public void setRecordArriveTime(Date recordArriveTime) {
        this.recordArriveTime = recordArriveTime;
    }

    public Integer getIsRegular() {
        return isRegular;
    }

    public void setIsRegular(Integer isRegular) {
        this.isRegular = isRegular;
    }

    public void setStationDimissingTime(Date stationDimissingTime) {
        this.stationDimissingTime = stationDimissingTime;
    }

    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public Long getRecordCustomerId() {
        return recordCustomerId;
    }

    public void setRecordCustomerId(Long recordCustomerId) {
        this.recordCustomerId = recordCustomerId;
    }

    public Integer getRecordOperationType() {
        return recordOperationType;
    }

    public void setRecordOperationType(Integer recordOperationType) {
        this.recordOperationType = recordOperationType;
    }

    public Date getRecordOperationTime() {
        return recordOperationTime;
    }

    public void setRecordOperationTime(Date recordOperationTime) {
        this.recordOperationTime = recordOperationTime;
    }

    public Long getRecordDeptId() {
        return recordDeptId;
    }

    public void setRecordDeptId(Long recordDeptId) {
        this.recordDeptId = recordDeptId;
    }

    public String getRecordDeptName() {
        return recordDeptName;
    }

    public void setRecordDeptName(String recordDeptName) {
        this.recordDeptName = recordDeptName;
    }

    public Date getRecordDimissingTime() {
        return recordDimissingTime;
    }

    public void setRecordDimissingTime(Date recordDimissingTime) {
        this.recordDimissingTime = recordDimissingTime;
    }

    public String getRecordDimissingReason() {
        return recordDimissingReason;
    }

    public void setRecordDimissingReason(String recordDimissingReason) {
        this.recordDimissingReason = recordDimissingReason;
    }

    public Date getRecordCreateTime() {
        return recordCreateTime;
    }

    public void setRecordCreateTime(Date recordCreateTime) {
        this.recordCreateTime = recordCreateTime;
    }

    public Long getRecordDeptIdBefore() {
        return recordDeptIdBefore;
    }

    public void setRecordDeptIdBefore(Long recordDeptIdBefore) {
        this.recordDeptIdBefore = recordDeptIdBefore;
    }

    public String getRecordStationNameBefore() {
        return recordStationNameBefore;
    }

    public void setRecordStationNameBefore(String recordStationNameBefore) {
        this.recordStationNameBefore = recordStationNameBefore;
    }

    public String getRecordStationNameAfter() {
        return recordStationNameAfter;
    }

    public void setRecordStationNameAfter(String recordStationNameAfter) {
        this.recordStationNameAfter = recordStationNameAfter;
    }

    public BigDecimal getRecordSalaryBefore() {
        return recordSalaryBefore;
    }

    public void setRecordSalaryBefore(BigDecimal recordSalaryBefore) {
        this.recordSalaryBefore = recordSalaryBefore;
    }

    public BigDecimal getRecordSalaryAfter() {
        return recordSalaryAfter;
    }

    public void setRecordSalaryAfter(BigDecimal recordSalaryAfter) {
        this.recordSalaryAfter = recordSalaryAfter;
    }


    private String startTimeStr;
    private String endTimeStr;

    public String getStartTimeStr() {
        return startTimeStr;
    }

    public void setStartTimeStr(String startTimeStr) {
        this.startTimeStr = startTimeStr;
    }

    public String getEndTimeStr() {
        return endTimeStr;
    }

    public void setEndTimeStr(String endTimeStr) {
        this.endTimeStr = endTimeStr;
    }
}
