package com.xtr.core.persistence.writer.company;

import com.xtr.api.domain.company.CompanyMsgsBean;

public interface CompanyMsgsWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    int insert(CompanyMsgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    int insertSelective(CompanyMsgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyMsgsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_msgs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyMsgsBean record);

    /**
     * 更新消息的状态为删除
     * @param cop
     * @return
     */
    int updateComMsgById(CompanyMsgsBean cop);

    /**
     * 更新状态为已读
     * @param msgId
     * @return
     */
    int updateHasReadById(Long msgId);
}