package com.xtr.core.persistence.writer.company;

import com.xtr.api.domain.company.CompanyNotesBean;

public interface CompanyNotesWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long noteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    int insert(CompanyNotesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    int insertSelective(CompanyNotesBean record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyNotesBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_notes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyNotesBean record);


}