package com.xtr.core.persistence.writer.company;

import com.xtr.api.domain.company.CompanyShebaoOrderBean;
import org.apache.ibatis.annotations.Param;

public interface CompanyShebaoOrderWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_order
     *
     * @mbggenerated
     */
    int insert(CompanyShebaoOrderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_order
     *
     * @mbggenerated
     */
    int insertSelective(CompanyShebaoOrderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyShebaoOrderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyShebaoOrderBean record);

    /**
     * 更新其他订单为历史订单
     * @param companyId
     * @param cityCode
     * @param id
     * @return
     */
    int updateOtherToDefault(@Param("companyId") long companyId, @Param("cityCode") String cityCode, @Param("currentId") Long id);

    /**
     * 更新企业订单信息
     * @param orderNumber
     * @param status
     * @return
     */
    int updateStatusByOrderNuber(@Param("orderNumber") String orderNumber, @Param("orderStatus") int status);

    /**
     * 更新所有未提交的订单
     * @return
     */
    int updateUnSubmitOrder();

    /**
     *
     * @param id
     * @return
     */
    int deleteCompanyOrderIfEmpty(@Param("id") Long id);

    /**
     * 更新该公司的未读账单为已读
     * @param companyId
     */
    void updateNoReadOrders(Long companyId);
}