package com.xtr.core.persistence.reader.customer;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.xtr.api.domain.customer.CustomerExpenseDetailBean;
import com.xtr.api.dto.customer.CustomerExpenseDto;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

public interface CustomerExpenseDetailReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_expense_detail
     *
     * @mbggenerated
     */
    CustomerExpenseDetailBean selectByPrimaryKey(Long id);

    /**
     * 报销列表
     * @param dto
     * @param startDate
     *@param pageBounds  @return
     */
    PageList<Map<String, Object>> selectPage(@Param("dto") CustomerExpenseDto dto, @Param("startDate") Date startDate, PageBounds pageBounds);

    /**
     * 查询用户报销记录
     * @param customerId
     * @return
     */
    List<CustomerExpenseDetailBean> selectExpense(@Param("customerId") long customerId, @Param("cycleId") Long cycleId);

    /**
     * 查询用户报销总额
     * @param customerId
     * @param cycleId
     * @return
     */
    BigDecimal selectCustomerExpenseSum(@Param("customerId") long customerId, @Param("cycleId") Long cycleId);

    /**
     * 查询未定额数量
     * @param companyId
     * @param startDate
     * @return
     */
    int selectUnsetCount(@Param("companyId") Long companyId, @Param("cycleId") long cycleId, @Param("startDate") Date startDate);
}