package com.xtr.core.persistence.reader.customer;

import com.xtr.api.domain.customer.CustomersStationBean;
import com.xtr.api.dto.customer.CustomersDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CustomersStationReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    CustomersStationBean selectByPrimaryKey(Long stationId);

    /**
     * 根据用户id查询岗位表
     * @param customerId
     * @return
     */
    CustomersStationBean selectByCustomerId(Long customerId);

    /**
     * 查询工号是否有重复
     * @param list
     * @return
     */
    List<CustomersStationBean> selectStatonNumberForeach (@Param("list") List<String> list,@Param("companyId") Long companyId);

    /**
     * 根据入职状态查询员工岗位信息
     * @param map
     * @return
     */
    List<CustomersStationBean> selectByNoRegular(Map map);
}