package com.xtr.core.persistence.reader.customer;

import com.xtr.api.domain.customer.CustomersPersonalBean;
import com.xtr.api.dto.customer.CustomersDto;

public interface CustomersPersonalReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    CustomersPersonalBean selectByPrimaryKey(Long personalId);

    /**
     * 根据用户id查询用户个人信息
     * @param customerId
     * @return
     */
    CustomersPersonalBean selectByCustomerId(Long customerId);
}