package com.xtr.core.persistence.reader.customer;

import com.xtr.api.domain.customer.CustomersRecordBean;
import com.xtr.api.dto.customer.CustomersDto;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface CustomersRecordReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_record
     *
     * @mbggenerated
     */
    CustomersRecordBean selectByPrimaryKey(Long recordId);

    /**
     * 根据用户id查询用户记录表
     * @param customerId
     * @return
     */
    CustomersRecordBean selectByCustomerId(Long customerId);

    /**
     *根据用户id查询记录,不包括删除的记录
     * @param customerId
     * @return
     */
    List<CustomersDto> selectRecordByCustomerId(Long customerId);

    /**
     * 获取调薪人数
     * @param customersDto
     * @return
     */
    List<CustomersDto> selectRecordCountBySaraly(CustomersDto customersDto);

    /**
     *查询前一天所有待转正的员工
     * @param  map
     * @return
     */
    List<CustomersRecordBean> selectTranferPosition(Map map);

    /**
     * 查询前一天所有待离职的员工
     * @param map
     * @return
     */
    List<CustomersRecordBean> selectDimission(Map map);

    /**
     * 批量获取待离职的员工
     * @param list
     * @return
     */
    List<CustomersRecordBean> selectWillLeaveBatch(@Param("list") List<Long> list, @Param("nowTime") Date nowTime);

    /**
     * 查询当前是否有待调岗的记录
     * @param
     * @return
     */
    List<CustomersRecordBean> selectFutureTranferPosition(Map map);
}