package com.xtr.core.persistence.reader.customer;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.xtr.api.domain.customer.CustomerShebaoBean;
import com.xtr.api.domain.customer.CustomerShebaoOrderBean;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface CustomerShebaoReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_shebao
     *
     * @mbggenerated
     */
    CustomerShebaoBean selectByPrimaryKey(Long id);

    /**
     * 首页分页查询
     * @param bean
     * @param pageBounds
     * @return
     */
    PageList<Map> selectPage(CustomerShebaoBean bean, PageBounds pageBounds);

    /**
     * 根据员工获取社保基本信息
     * @param customerId
     * @return
     */
    CustomerShebaoBean selectByCustomerId(@Param("customerId") long customerId);

    /**
     * 根据员工ID批量查询员工社保公积金信息
     * @param list
     * @return
     */
    List<CustomerShebaoBean> selectBatchForCustomerId(List<Long> list);

    /**
     * 查询所有汇缴员工
     * @param companyId
     * @param joinCity
     * @param requireType
     * @return
     */
    List<CustomerShebaoBean> selectKeepCustomer(@Param("companyId") long companyId, @Param("joinCity") String joinCity, @Param("requireType") int requireType, @Param("orderDate")Date orderDate);

    /**
     * 查询所有停缴员工
     * @param companyId
     * @param joinCity
     * @param orderDate
     * @return
     */
    List<CustomerShebaoBean> selectStopCustomer(@Param("companyId") long companyId, @Param("joinCity") String joinCity, @Param("requireType") int requireType, @Param("orderDate")Date orderDate);

    /**
     * 查询缴纳人数
     * @param code
     * @param memberCompanyId
     * @return
     */
    int selectKeepCustomerCount(@Param("stype") int code, @Param("memberCompanyId") Long memberCompanyId);

    /**
     * 根据公司查询缴纳地区
     * @param companyId
     * @return
     */
    List<Map> selectJoinCityByCompanyId(@Param("companyId") long companyId);

    Map selectBaseInfo(Long customerId);

    /**
     * 查询当前公司缴纳的社保和公积金
     * @param companyId
     * @return
     */
    List<Map> selectKeepSbAndGjjType(@Param("companyId") long companyId);
}