package com.xtr.core.persistence.reader.app;

import com.xtr.api.domain.app.AppQuestionFeedbackBean;

public interface AppQuestionFeedbackReaderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_question_feedback
     *
     * @mbggenerated
     */
    AppQuestionFeedbackBean selectByPrimaryKey(Long feedbackId);


}