package com.xtr.api.service.customer;

import com.xtr.api.basic.ResultResponse;
import com.xtr.api.domain.customer.CustomerRechargesBean;
import com.xtr.api.dto.customer.CustomerReachrgeDto;
import com.xtr.api.dto.gateway.response.NotifyResponse;
import com.xtr.comm.basic.BusinessException;

import java.io.File;
import java.util.List;

/**
 * <p>用户充值提现</p>
 *
 * @author 任齐
 * @createTime: 2016/7/8 11:24
 */
public interface CustomerRechargesService {

    /**
     * 员工提现
     *
     * @param customerRechargesBean
     * @return
     * @throws BusinessException
     */
    int customerWithdrawals(CustomerRechargesBean customerRechargesBean) throws BusinessException;

    /**
     * 根据企业id删除
     *
     * @param companyId
     */
    void deleteByCompanyId(Long companyId);

    /**
     * 分页查询个人提现批次
     *
     * @param startTime
     * @param state
     * @param auditName
     * @param pageIndex
     * @param pageSize
     * @return
     */
    ResultResponse selectBatchPageList(String startTime, Integer state, String auditName, int pageIndex, int pageSize);

    /**
     * 分页查询个人充值提现详情
     *
     * @param customerRechargesBean
     * @param pageIndex
     * @param pageSize
     * @return
     */
    ResultResponse selectPageList(CustomerRechargesBean customerRechargesBean, int pageIndex, int pageSize);

    /**
     * 查询提现列表
     *
     * @param batchNumber
     * @return
     */
    List<CustomerReachrgeDto> selectDetailList(String batchNumber);

    /**
     * 审核提现
     *
     * @param memberId
     * @param auditType
     * @param batchNumber
     * @throws BusinessException
     */
    void auditWithdrawals(Long memberId, Integer auditType, String batchNumber) throws BusinessException;

    /**
     * 生成一个批次的工资单
     *
     * @param batchNumber
     * @param webRoot
     * @param payTemplatePath
     * @param downloadPath
     * @return
     */
    File generatorSalaryExcel(String batchNumber, String webRoot, String payTemplatePath, String downloadPath);

    /**
     * 根据第三方平台获取所有待审批的提现申请
     *
     * @return
     */
    List<CustomerRechargesBean> getAllWithdrawals(Integer rechargeStation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_recharges
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerRechargesBean record);

    /**
     * 处理京东回调
     * @param response
     */
    void doJdResponse(NotifyResponse response);

    /**
     *根据第三方平台获取所有社保公积金补退的提现申请
     * @param rechargeStation
     * @return
     */
    List<CustomerRechargesBean> getBackWithdrawals(Integer rechargeStation);
}
