package com.xtr.api.service.customer;

import com.xtr.api.domain.customer.CustomersPersonalBean;

/**
 * @author 王志新 robert.wang@xintairuan.com
 * @createTime:2016/8/12 17:55
 */
public interface CustomersPersonalService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    CustomersPersonalBean selectByPrimaryKey(Long personalId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long personalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int insert(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int insertSelective(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomersPersonalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_personal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomersPersonalBean record);

    /**
     * 根据用户id查询用户个人信息
     * @param customerId
     * @return
     */
    CustomersPersonalBean selectByCustomerId(Long customerId);
}
