package com.xtr.api.service.customer;

import com.xtr.api.basic.ResultResponse;
import com.xtr.api.domain.customer.CustomersStationBean;
import com.xtr.comm.basic.BusinessException;

import java.util.List;
import java.util.Map;

/**
 * @author 王志新 robert.wang@xintairuan.com
 * @createTime:2016/8/12 17:55
 */
public interface CustomersStationService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    CustomersStationBean selectByPrimaryKey(Long stationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long stationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int insert(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int insertSelective(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomersStationBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomersStationBean record);

    /**
     * 移动员工部门
     * @param depId
     * @param empId
     * @return
     */
    boolean moveCustomerDept(Long depId, long empId, long companyId);

    /**
     * 根据customerId查询员工岗位信息
     * @param customerId
     * @return
     */
    CustomersStationBean selectCutomerStationByCustomerId(long customerId);

    /**
     * 查询工号是否有重复
     * @param list
     * @return
     */
//    List<CustomersStationBean> selectStatonNumberForeach (List<String> list,Long companyId);

    /**
     * 根据入职状态查询所有员工岗位信息
     * @param map
     * @return
     */
    List<CustomersStationBean> selectByNoRegular(Map map);

    /**
     * 自动更新员工状态为已转正（必须为入职的员工）
     * @param cus
     * @return
     */
    int updateStateByCustomerId(CustomersStationBean cus);

    /**
     * 批量插入员工岗位信息
     * @param list
     * @return
     */
    int insertBatch(List<CustomersStationBean> list);

    /**
     * 根据用户id更新岗位信息
     * @param customersStationBean
     * @return
     */
    int updateByCustomerId(CustomersStationBean customersStationBean);

    /**
     * 查询工号是否有重复
     * @param list
     * @return
     */
    Map<Integer,List<CustomersStationBean>> selectStatonNumberForeach (List<String> list, Long companyId, int type, long customerId);

    /**
     * 更新用户岗位信息
     * @param customersStationBean
     * @param companyId
     * @return
     */
    ResultResponse modifyCustomerStation(CustomersStationBean customersStationBean, Long companyId) throws Exception;

    /**
     * 更新用户岗位信息
     *
     * @param customersStationBean
     * @param companyId
     * @return
     */
    ResultResponse modifyCustomerStationNew(CustomersStationBean customersStationBean, Long companyId) throws Exception;
}
